unit rSale;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Db, Qrctrls, QuickRpt, ExtCtrls, QRExport, 
  rDBDataReport, DBClient, AbmesClientDataSet;

type
  TrptSale = class(TDBDataReport)
    bndTitle: TQRBand;
    QRLabel1: TQRLabel;
    QRShape1: TQRShape;
    QRLabel2: TQRLabel;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel7: TQRLabel;
    QRShape2: TQRShape;
    QRDBText1: TQRDBText;
    QRShape3: TQRShape;
    QRDBText2: TQRDBText;
    QRShape4: TQRShape;
    QRDBText3: TQRDBText;
    QRShape5: TQRShape;
    QRDBText4: TQRDBText;
    QRShape6: TQRShape;
    QRDBText5: TQRDBText;
    QRShape7: TQRShape;
    QRLabel8: TQRLabel;
    QRShape8: TQRShape;
    QRDBText6: TQRDBText;
    QRShape9: TQRShape;
    QRDBText7: TQRDBText;
    QRShape10: TQRShape;
    QRLabel9: TQRLabel;
    QRShape11: TQRShape;
    QRDBText8: TQRDBText;
    QRLabel10: TQRLabel;
    QRShape12: TQRShape;
    QRDBText9: TQRDBText;
    QRLabel11: TQRLabel;
    QRShape13: TQRShape;
    QRDBText10: TQRDBText;
    QRLabel12: TQRLabel;
    QRShape14: TQRShape;
    QRLabel13: TQRLabel;
    QRLabel14: TQRLabel;
    QRShape15: TQRShape;
    QRDBText11: TQRDBText;
    QRLabel15: TQRLabel;
    QRShape16: TQRShape;
    QRDBText12: TQRDBText;
    QRShape17: TQRShape;
    QRDBText13: TQRDBText;
    QRShape18: TQRShape;
    QRDBText14: TQRDBText;
    QRShape19: TQRShape;
    QRDBText15: TQRDBText;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel20: TQRLabel;
    QRShape20: TQRShape;
    QRLabel21: TQRLabel;
    QRLabel22: TQRLabel;
    QRShape21: TQRShape;
    QRDBText16: TQRDBText;
    QRShape22: TQRShape;
    QRDBText17: TQRDBText;
    QRLabel23: TQRLabel;
    QRShape23: TQRShape;
    QRDBText18: TQRDBText;
    QRDBText19: TQRDBText;
    QRLabel24: TQRLabel;
    QRShape24: TQRShape;
    QRDBText20: TQRDBText;
    QRDBText21: TQRDBText;
    QRLabel25: TQRLabel;
    QRShape25: TQRShape;
    QRDBText22: TQRDBText;
    QRLabel26: TQRLabel;
    QRShape26: TQRShape;
    QRDBText23: TQRDBText;
    QRShape27: TQRShape;
    QRDBText24: TQRDBText;
    QRLabel27: TQRLabel;
    QRShape28: TQRShape;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRShape29: TQRShape;
    QRDBText25: TQRDBText;
    QRLabel31: TQRLabel;
    QRShape30: TQRShape;
    QRDBText26: TQRDBText;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    QRShape31: TQRShape;
    QRDBText27: TQRDBText;
    QRShape32: TQRShape;
    QRDBText28: TQRDBText;
    QRShape33: TQRShape;
    QRDBText29: TQRDBText;
    QRShape34: TQRShape;
    QRDBText30: TQRDBText;
    QRShape35: TQRShape;
    QRLabel35: TQRLabel;
    QRLabel36: TQRLabel;
    QRShape36: TQRShape;
    QRDBText31: TQRDBText;
    QRLabel37: TQRLabel;
    QRShape37: TQRShape;
    QRDBText32: TQRDBText;
    QRShape38: TQRShape;
    QRLabel38: TQRLabel;
    QRShape39: TQRShape;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRShape40: TQRShape;
    QRDBText33: TQRDBText;
    QRLabel41: TQRLabel;
    QRShape41: TQRShape;
    QRDBText34: TQRDBText;
    QRLabel42: TQRLabel;
    QRShape42: TQRShape;
    QRDBText35: TQRDBText;
    QRDBText36: TQRDBText;
    QRShape43: TQRShape;
    QRDBText37: TQRDBText;
    QRShape44: TQRShape;
    QRLabel43: TQRLabel;
    QRShape45: TQRShape;
    QRDBText38: TQRDBText;
    lblWastingSale: TQRLabel;
    shpWastingSaleBranch: TQRShape;
    txtWastingSaleBranch: TQRDBText;
    shpWastingSaleNo: TQRShape;
    txtWastingSaleNo: TQRDBText;
    QRShape48: TQRShape;
    QRLabel45: TQRLabel;
    QRShape49: TQRShape;
    QRDBText41: TQRDBText;
    QRLabel46: TQRLabel;
    QRShape50: TQRShape;
    QRShape51: TQRShape;
    QRDBText42: TQRDBText;
    QRLabel47: TQRLabel;
    QRShape53: TQRShape;
    QRLabel49: TQRLabel;
    QRShape54: TQRShape;
    QRDBText44: TQRDBText;
    QRLabel50: TQRLabel;
    QRShape55: TQRShape;
    QRDBText45: TQRDBText;
    QRLabel51: TQRLabel;
    QRShape56: TQRShape;
    QRDBText46: TQRDBText;
    QRDBText47: TQRDBText;
    QRShape46: TQRShape;
    QRDBText39: TQRDBText;
    QRLabel44: TQRLabel;
    QRShape57: TQRShape;
    QRDBText48: TQRDBText;
    QRLabel53: TQRLabel;
    QRShape58: TQRShape;
    QRDBText49: TQRDBText;
    QRLabel54: TQRLabel;
    QRLabel55: TQRLabel;
    QRShape52: TQRShape;
    QRLabel48: TQRLabel;
    QRLabel56: TQRLabel;
    QRShape59: TQRShape;
    QRDBText43: TQRDBText;
    QRLabel57: TQRLabel;
    QRShape60: TQRShape;
    QRDBText50: TQRDBText;
    QRShape61: TQRShape;
    QRDBText51: TQRDBText;
    QRLabel58: TQRLabel;
    QRShape62: TQRShape;
    QRDBText52: TQRDBText;
    QRLabel59: TQRLabel;
    QRShape63: TQRShape;
    QRDBText53: TQRDBText;
    QRLabel60: TQRLabel;
    QRShape64: TQRShape;
    QRLabel61: TQRLabel;
    QRLabel62: TQRLabel;
    QRShape65: TQRShape;
    QRDBText54: TQRDBText;
    QRLabel63: TQRLabel;
    QRShape66: TQRShape;
    QRDBText55: TQRDBText;
    QRShape67: TQRShape;
    QRDBText56: TQRDBText;
    QRLabel64: TQRLabel;
    QRShape68: TQRShape;
    QRDBText57: TQRDBText;
    QRLabel65: TQRLabel;
    QRLabel66: TQRLabel;
    QRShape69: TQRShape;
    QRDBText58: TQRDBText;
    QRLabel67: TQRLabel;
    QRShape70: TQRShape;
    QRDBText59: TQRDBText;
    QRShape71: TQRShape;
    QRLabel68: TQRLabel;
    QRLabel69: TQRLabel;
    QRShape72: TQRShape;
    QRDBText60: TQRDBText;
    QRLabel70: TQRLabel;
    QRShape73: TQRShape;
    QRDBText61: TQRDBText;
    QRLabel71: TQRLabel;
    QRShape74: TQRShape;
    QRDBText62: TQRDBText;
    QRShape75: TQRShape;
    QRLabel72: TQRLabel;
    QRShape76: TQRShape;
    QRLabel73: TQRLabel;
    QRLabel74: TQRLabel;
    QRLabel75: TQRLabel;
    QRShape77: TQRShape;
    QRDBText63: TQRDBText;
    QRShape78: TQRShape;
    QRDBText64: TQRDBText;
    QRLabel76: TQRLabel;
    rctClientProductSignature: TQRShape;
    lblClientProductSignatureData: TQRDBText;
    lblClientProductSignature: TQRLabel;
    QRShape80: TQRShape;
    QRLabel78: TQRLabel;
    QRLabel79: TQRLabel;
    QRShape81: TQRShape;
    QRDBText66: TQRDBText;
    QRLabel80: TQRLabel;
    QRShape82: TQRShape;
    QRDBText67: TQRDBText;
    QRLabel81: TQRLabel;
    QRShape83: TQRShape;
    QRDBText68: TQRDBText;
    QRLabel82: TQRLabel;
    QRShape84: TQRShape;
    QRDBText69: TQRDBText;
    QRLabel83: TQRLabel;
    QRShape85: TQRShape;
    QRDBText70: TQRDBText;
    QRLabel84: TQRLabel;
    QRShape86: TQRShape;
    QRDBText71: TQRDBText;
    QRShape87: TQRShape;
    QRLabel85: TQRLabel;
    QRShape88: TQRShape;
    QRLabel86: TQRLabel;
    QRLabel87: TQRLabel;
    QRShape89: TQRShape;
    QRDBText72: TQRDBText;
    QRLabel88: TQRLabel;
    QRShape90: TQRShape;
    QRDBText73: TQRDBText;
    QRDBText74: TQRDBText;
    QRLabel89: TQRLabel;
    QRShape91: TQRShape;
    QRDBText76: TQRDBText;
    QRLabel90: TQRLabel;
    QRShape92: TQRShape;
    QRDBText77: TQRDBText;
    QRLabel91: TQRLabel;
    QRShape93: TQRShape;
    QRDBText78: TQRDBText;
    QRDBText79: TQRDBText;
    QRDBText80: TQRDBText;
    QRDBText81: TQRDBText;
    QRDBText82: TQRDBText;
    QRLabel92: TQRLabel;
    QRDBText75: TQRDBText;
    QRDBText83: TQRDBText;
    bndColumnHeader: TQRBand;
    bndDetail: TQRBand;
    QRShape95: TQRShape;
    QRLabel94: TQRLabel;
    QRShape96: TQRShape;
    QRLabel95: TQRLabel;
    QRShape97: TQRShape;
    QRLabel96: TQRLabel;
    QRShape98: TQRShape;
    QRLabel97: TQRLabel;
    QRShape47: TQRShape;
    QRLabel98: TQRLabel;
    QRShape94: TQRShape;
    QRLabel99: TQRLabel;
    QRShape99: TQRShape;
    QRLabel100: TQRLabel;
    QRShape100: TQRShape;
    QRLabel101: TQRLabel;
    QRShape101: TQRShape;
    QRLabel102: TQRLabel;
    QRShape102: TQRShape;
    QRLabel93: TQRLabel;
    QRShape103: TQRShape;
    QRLabel103: TQRLabel;
    QRShape104: TQRShape;
    QRLabel104: TQRLabel;
    QRShape105: TQRShape;
    QRShape106: TQRShape;
    QRLabel106: TQRLabel;
    QRShape107: TQRShape;
    QRLabel107: TQRLabel;
    QRShape108: TQRShape;
    QRLabel108: TQRLabel;
    QRShape109: TQRShape;
    QRShape110: TQRShape;
    QRLabel109: TQRLabel;
    QRLabel110: TQRLabel;
    QRShape111: TQRShape;
    QRShape112: TQRShape;
    QRShape113: TQRShape;
    QRShape114: TQRShape;
    QRShape115: TQRShape;
    QRShape116: TQRShape;
    QRShape117: TQRShape;
    QRShape118: TQRShape;
    QRShape119: TQRShape;
    QRShape120: TQRShape;
    QRShape121: TQRShape;
    QRShape122: TQRShape;
    QRShape123: TQRShape;
    QRShape124: TQRShape;
    QRShape125: TQRShape;
    QRDBText40: TQRDBText;
    QRDBText84: TQRDBText;
    QRDBText85: TQRDBText;
    QRDBText86: TQRDBText;
    QRDBText87: TQRDBText;
    QRDBText88: TQRDBText;
    QRDBText89: TQRDBText;
    QRDBText90: TQRDBText;
    QRDBText91: TQRDBText;
    QRDBText92: TQRDBText;
    QRDBText93: TQRDBText;
    QRDBText94: TQRDBText;
    QRDBText95: TQRDBText;
    QRDBText96: TQRDBText;
    QRDBText97: TQRDBText;
    QRLabel52: TQRLabel;
    QRShape126: TQRShape;
    QRLabel111: TQRLabel;
    QRShape127: TQRShape;
    QRLabel112: TQRLabel;
    QRShape128: TQRShape;
    QRLabel113: TQRLabel;
    QRShape132: TQRShape;
    QRLabel114: TQRLabel;
    QRShape133: TQRShape;
    QRLabel115: TQRLabel;
    QRShape134: TQRShape;
    QRLabel116: TQRLabel;
    QRShape135: TQRShape;
    QRLabel117: TQRLabel;
    QRShape136: TQRShape;
    QRLabel118: TQRLabel;
    QRShape138: TQRShape;
    QRLabel120: TQRLabel;
    QRShape139: TQRShape;
    QRLabel121: TQRLabel;
    QRShape140: TQRShape;
    QRShape142: TQRShape;
    QRLabel124: TQRLabel;
    QRShape143: TQRShape;
    QRLabel125: TQRLabel;
    QRShape144: TQRShape;
    QRLabel126: TQRLabel;
    QRShape145: TQRShape;
    QRShape146: TQRShape;
    QRLabel127: TQRLabel;
    QRLabel128: TQRLabel;
    QRLabel119: TQRLabel;
    QRShape137: TQRShape;
    QRLabel122: TQRLabel;
    QRShape147: TQRShape;
    QRLabel129: TQRLabel;
    QRShape148: TQRShape;
    QRLabel130: TQRLabel;
    QRShape149: TQRShape;
    QRLabel131: TQRLabel;
    QRShape150: TQRShape;
    QRLabel132: TQRLabel;
    QRShape151: TQRShape;
    QRLabel133: TQRLabel;
    QRShape152: TQRShape;
    QRLabel134: TQRLabel;
    QRShape153: TQRShape;
    QRLabel135: TQRLabel;
    QRShape154: TQRShape;
    QRLabel136: TQRLabel;
    QRShape155: TQRShape;
    QRLabel137: TQRLabel;
    QRShape156: TQRShape;
    QRLabel138: TQRLabel;
    QRShape157: TQRShape;
    QRLabel139: TQRLabel;
    QRShape158: TQRShape;
    QRLabel140: TQRLabel;
    QRShape159: TQRShape;
    QRLabel141: TQRLabel;
    QRShape160: TQRShape;
    QRLabel142: TQRLabel;
    QRShape161: TQRShape;
    QRLabel143: TQRLabel;
    QRShape162: TQRShape;
    QRLabel144: TQRLabel;
    QRShape163: TQRShape;
    QRLabel145: TQRLabel;
    QRShape164: TQRShape;
    QRLabel146: TQRLabel;
    QRShape165: TQRShape;
    QRShape166: TQRShape;
    QRLabel147: TQRLabel;
    QRLabel148: TQRLabel;
    QRDBText98: TQRDBText;
    QRDBText99: TQRDBText;
    QRDBText100: TQRDBText;
    QRDBText101: TQRDBText;
    QRDBText102: TQRDBText;
    QRDBText103: TQRDBText;
    QRDBText104: TQRDBText;
    QRDBText105: TQRDBText;
    QRShape129: TQRShape;
    QRShape130: TQRShape;
    QRShape131: TQRShape;
    QRShape141: TQRShape;
    QRShape167: TQRShape;
    QRShape168: TQRShape;
    QRShape169: TQRShape;
    QRShape170: TQRShape;
    QRShape171: TQRShape;
    QRShape172: TQRShape;
    QRShape173: TQRShape;
    QRShape174: TQRShape;
    QRShape175: TQRShape;
    QRShape176: TQRShape;
    QRShape177: TQRShape;
    QRDBText106: TQRDBText;
    QRDBText107: TQRDBText;
    QRDBText108: TQRDBText;
    QRDBText109: TQRDBText;
    QRDBText110: TQRDBText;
    QRDBText111: TQRDBText;
    QRDBText112: TQRDBText;
    QRShape178: TQRShape;
    QRShape179: TQRShape;
    QRShape180: TQRShape;
    QRShape181: TQRShape;
    QRShape182: TQRShape;
    QRShape183: TQRShape;
    QRShape184: TQRShape;
    QRShape185: TQRShape;
    QRShape186: TQRShape;
    QRShape187: TQRShape;
    QRShape188: TQRShape;
    QRShape189: TQRShape;
    QRShape190: TQRShape;
    QRShape191: TQRShape;
    QRShape192: TQRShape;
    QRDBText113: TQRDBText;
    QRDBText114: TQRDBText;
    QRDBText115: TQRDBText;
    QRDBText116: TQRDBText;
    QRDBText117: TQRDBText;
    QRDBText118: TQRDBText;
    QRDBText119: TQRDBText;
    QRDBText120: TQRDBText;
    QRDBText121: TQRDBText;
    QRDBText122: TQRDBText;
    QRDBText123: TQRDBText;
    QRDBText124: TQRDBText;
    QRDBText125: TQRDBText;
    QRDBText126: TQRDBText;
    QRDBText127: TQRDBText;
    QRShape193: TQRShape;
    QRLabel123: TQRLabel;
    QRShape194: TQRShape;
    QRLabel149: TQRLabel;
    QRShape195: TQRShape;
    QRLabel150: TQRLabel;
    QRShape196: TQRShape;
    QRLabel151: TQRLabel;
    QRShape197: TQRShape;
    QRLabel152: TQRLabel;
    QRShape198: TQRShape;
    QRLabel153: TQRLabel;
    QRShape199: TQRShape;
    QRLabel154: TQRLabel;
    QRShape200: TQRShape;
    QRLabel155: TQRLabel;
    QRShape201: TQRShape;
    QRLabel156: TQRLabel;
    QRShape202: TQRShape;
    QRLabel157: TQRLabel;
    QRShape203: TQRShape;
    QRLabel158: TQRLabel;
    QRShape204: TQRShape;
    QRLabel159: TQRLabel;
    QRShape205: TQRShape;
    QRLabel160: TQRLabel;
    QRShape206: TQRShape;
    QRLabel161: TQRLabel;
    QRShape207: TQRShape;
    QRLabel162: TQRLabel;
    QRShape208: TQRShape;
    QRLabel163: TQRLabel;
    QRShape209: TQRShape;
    QRShape210: TQRShape;
    QRLabel164: TQRLabel;
    QRLabel165: TQRLabel;
    QRShape211: TQRShape;
    QRLabel166: TQRLabel;
    QRShape212: TQRShape;
    QRLabel167: TQRLabel;
    QRShape213: TQRShape;
    QRLabel168: TQRLabel;
    QRShape214: TQRShape;
    QRLabel169: TQRLabel;
    QRShape215: TQRShape;
    QRLabel170: TQRLabel;
    QRShape216: TQRShape;
    QRLabel171: TQRLabel;
    QRShape217: TQRShape;
    QRLabel172: TQRLabel;
    QRShape218: TQRShape;
    QRLabel173: TQRLabel;
    QRShape219: TQRShape;
    QRLabel174: TQRLabel;
    QRShape220: TQRShape;
    QRLabel175: TQRLabel;
    QRShape221: TQRShape;
    QRShape222: TQRShape;
    QRLabel176: TQRLabel;
    QRShape223: TQRShape;
    QRLabel177: TQRLabel;
    QRShape224: TQRShape;
    QRLabel178: TQRLabel;
    QRShape225: TQRShape;
    QRShape226: TQRShape;
    QRLabel179: TQRLabel;
    QRLabel180: TQRLabel;
    QRLabel181: TQRLabel;
    QRShape227: TQRShape;
    QRLabel182: TQRLabel;
    QRShape228: TQRShape;
    QRLabel183: TQRLabel;
    QRShape229: TQRShape;
    QRLabel184: TQRLabel;
    QRShape230: TQRShape;
    QRLabel185: TQRLabel;
    QRShape231: TQRShape;
    QRLabel186: TQRLabel;
    QRShape232: TQRShape;
    QRLabel187: TQRLabel;
    QRShape233: TQRShape;
    QRLabel188: TQRLabel;
    QRShape234: TQRShape;
    QRLabel189: TQRLabel;
    QRShape235: TQRShape;
    QRLabel190: TQRLabel;
    QRShape236: TQRShape;
    QRLabel191: TQRLabel;
    QRShape237: TQRShape;
    QRLabel192: TQRLabel;
    QRShape238: TQRShape;
    QRLabel193: TQRLabel;
    QRShape239: TQRShape;
    QRLabel194: TQRLabel;
    QRShape240: TQRShape;
    QRLabel195: TQRLabel;
    QRShape241: TQRShape;
    QRLabel196: TQRLabel;
    QRShape242: TQRShape;
    QRLabel197: TQRLabel;
    QRShape243: TQRShape;
    QRLabel198: TQRLabel;
    QRShape244: TQRShape;
    QRLabel199: TQRLabel;
    QRShape245: TQRShape;
    QRLabel200: TQRLabel;
    QRShape246: TQRShape;
    QRShape247: TQRShape;
    QRLabel201: TQRLabel;
    QRLabel202: TQRLabel;
    QRShape248: TQRShape;
    QRShape249: TQRShape;
    QRShape250: TQRShape;
    QRShape251: TQRShape;
    QRShape252: TQRShape;
    QRShape253: TQRShape;
    QRShape254: TQRShape;
    QRShape255: TQRShape;
    QRShape256: TQRShape;
    QRShape257: TQRShape;
    QRShape258: TQRShape;
    QRShape259: TQRShape;
    QRShape260: TQRShape;
    QRShape261: TQRShape;
    QRShape262: TQRShape;
    QRDBText128: TQRDBText;
    QRDBText129: TQRDBText;
    QRDBText130: TQRDBText;
    QRDBText131: TQRDBText;
    QRDBText132: TQRDBText;
    QRDBText133: TQRDBText;
    QRDBText134: TQRDBText;
    QRDBText135: TQRDBText;
    QRDBText136: TQRDBText;
    QRDBText137: TQRDBText;
    QRDBText138: TQRDBText;
    QRDBText139: TQRDBText;
    QRDBText140: TQRDBText;
    QRDBText141: TQRDBText;
    QRDBText142: TQRDBText;
    QRDBText143: TQRDBText;
    QRDBText144: TQRDBText;
    QRDBText145: TQRDBText;
    QRDBText146: TQRDBText;
    QRDBText147: TQRDBText;
    QRDBText148: TQRDBText;
    QRDBText149: TQRDBText;
    QRDBText150: TQRDBText;
    QRShape263: TQRShape;
    QRShape264: TQRShape;
    QRShape265: TQRShape;
    QRShape266: TQRShape;
    QRShape267: TQRShape;
    QRShape268: TQRShape;
    QRShape269: TQRShape;
    QRShape270: TQRShape;
    QRShape271: TQRShape;
    QRShape272: TQRShape;
    QRShape273: TQRShape;
    QRShape274: TQRShape;
    QRShape275: TQRShape;
    QRShape276: TQRShape;
    QRShape277: TQRShape;
    QRDBText151: TQRDBText;
    QRDBText152: TQRDBText;
    QRDBText153: TQRDBText;
    QRDBText154: TQRDBText;
    QRDBText155: TQRDBText;
    QRDBText156: TQRDBText;
    QRDBText157: TQRDBText;
    QRShape278: TQRShape;
    QRShape279: TQRShape;
    QRShape280: TQRShape;
    QRShape281: TQRShape;
    QRShape282: TQRShape;
    QRShape283: TQRShape;
    QRShape284: TQRShape;
    QRShape285: TQRShape;
    QRShape286: TQRShape;
    QRShape287: TQRShape;
    QRShape288: TQRShape;
    QRShape289: TQRShape;
    QRShape290: TQRShape;
    QRShape291: TQRShape;
    QRShape292: TQRShape;
    QRDBText158: TQRDBText;
    QRDBText159: TQRDBText;
    QRDBText160: TQRDBText;
    QRDBText161: TQRDBText;
    QRDBText162: TQRDBText;
    QRDBText163: TQRDBText;
    QRDBText164: TQRDBText;
    QRDBText165: TQRDBText;
    QRDBText166: TQRDBText;
    QRDBText167: TQRDBText;
    QRDBText168: TQRDBText;
    QRDBText169: TQRDBText;
    QRDBText170: TQRDBText;
    QRDBText171: TQRDBText;
    QRDBText172: TQRDBText;
    QRShape293: TQRShape;
    QRLabel203: TQRLabel;
    QRDBText173: TQRDBText;
    QRLabel105: TQRLabel;
    procedure QuickRepBeforePrint(Sender: TCustomQuickRep;
      var PrintReport: Boolean);
  private
    { Private declarations }
  protected
    procedure InternalPrintReport; override;
    function RepositionTaggedItemsEnabled: Boolean; override;
    function GetRepositionDelta: Integer; override;
    function GetColumnHeaderBandHeight: Integer; override;
  public
    { Public declarations }
  end;

implementation

uses uProducts, uProductClientUtils, uClientUtils;

{$R *.DFM}

function TrptSale.GetColumnHeaderBandHeight: Integer;
begin
  Result:= 86;
end;

function TrptSale.GetRepositionDelta: Integer;
begin
  Result:= 56;
end;

procedure TrptSale.InternalPrintReport;
var
  i: Integer;
begin
  for i:= 0 to ComponentCount - 1 do
    if (Components[i] is TQRPrintable) then
      with (Components[i] as TQRPrintable) do
        if (Parent = bndTitle) then
          Enabled:=
            (Tag = 0) or
            (not Assigned(ReportDataSet) and (ParamsDataSet.FieldByName('MANUFACTURE_QUANTITY').AsFloat > 0));

  if Assigned(ReportDataSet) then
    bndTitle.Height:= 307
  else
    bndTitle.Height:= 675;

  bndColumnHeader.Enabled:= Assigned(ReportDataSet);
  bndDetail.Enabled:= bndColumnHeader.Enabled;

  inherited;
end;

procedure TrptSale.QuickRepBeforePrint(Sender: TCustomQuickRep;
  var PrintReport: Boolean);
var
  ProductClass: TProductClass;
  MsgParams: TStrings;
begin
  inherited;

  ProductClass:= IntToProductClass(ParamsDataSet.FieldByName('PRODUCT_CLASS_CODE').AsInteger);

  lblClientProductSignature.Enabled:= (ProductClass <> pcFinancial);
  lblClientProductSignatureData.Enabled:= (ProductClass <> pcFinancial);
  rctClientProductSignature.Enabled:= (ProductClass <> pcFinancial);

  MsgParams:= uProductClientUtils.CreateCommonMsgParams(LoginContext, ProductClass);     
  try
    RecursivelyFormatCaptions(Self, MsgParams);
  finally
    FreeAndNil(MsgParams);
  end;
end;

function TrptSale.RepositionTaggedItemsEnabled: Boolean;
begin
  Result:= Assigned(ReportDataSet);
end;

end.
