program SembiumClient;

{$R 'SembiumClientManifest.res' 'SembiumClientManifest.rc'}
{$R 'ClientVersionInfo.res' '..\..\App\ClientVersionInfo.rc'}
{$R 'ServerMessages.res' 'ServerMessages.rc'}
{$R 'DBTextMessages.res' 'DBTextMessages.rc'}
{$R 'App.res' '..\..\App\App.rc'}

uses
  uLocaleFix in '..\Common\uLocaleFix.pas',
  uLanguageOverride in 'uLanguageOverride.pas',
  MidasLib,
  SysUtils,
  Forms,
  uUtils in '..\Common\uUtils.pas',
  uXMLUtils in '..\Common\uXMLUtils.pas',
  xChosenNodes in '..\Common\xChosenNodes.pas',
  uProducts in '..\Common\uProducts.pas',
  uPeriods in '..\Common\uPeriods.pas',
  uProcesses in '..\Common\uProcesses.pas',
  uDealTypes in '..\Common\uDealTypes.pas',
  uCompanyKinds in '..\Common\uCompanyKinds.pas',
  uSaleChangeTypes in '..\Common\uSaleChangeTypes.pas',
  uSaleOrderTypes in '..\Common\uSaleOrderTypes.pas',
  uSalesCommon in '..\Common\uSalesCommon.pas',
  uTreeNodes in '..\Common\uTreeNodes.pas',
  uTreeNodeParams in '..\Common\uTreeNodeParams.pas',
  uGroupSales in '..\Common\uGroupSales.pas',
  uQuantityDeficitFieldNames in '..\Common\uQuantityDeficitFieldNames.pas',
  uLoginContext in '..\Common\uLoginContext.pas',
  uModelMovementTypes in '..\Common\uModelMovementTypes.pas',
  uMaterialListLineChanges in '..\Common\uMaterialListLineChanges.pas',
  uOperationTypes in '..\Common\uOperationTypes.pas',
  uSpecTypes in '..\Common\uSpecTypes.pas',
  uProductionLevels in '..\Common\uProductionLevels.pas',
  uUserActivityConsts in '..\Common\uUserActivityConsts.pas',
  uClientUtils in 'uClientUtils.pas',
  fMain in 'fMain.pas' {fmMain},
  dBaseDataModule in 'Abstract\dBaseDataModule.pas' {BaseDataModule: TDataModule},
  dMain in 'dMain.pas' {dmMain: TDataModule},
  fReportParent in 'Abstract\fReportParent.pas' {fmReportParent},
  rBaseReport in 'Abstract\rBaseReport.pas' {BaseReport: TQuickRep},
  rDBDataReport in 'Abstract\rDBDataReport.pas' {DBDataReport: TQuickRep},
  rMasterDetailReport in 'Abstract\rMasterDetailReport.pas' {MasterDetailReport: TQuickRep},
  fBaseForm in 'Abstract\fBaseForm.pas' {BaseForm},
  fButtonForm in 'Abstract\fButtonForm.pas' {ButtonForm},
  fDataForm in 'Abstract\fDataForm.pas' {DataForm},
  fDBDataForm in 'Abstract\fDBDataForm.pas' {DBDataForm},
  fEditForm in 'Abstract\fEditForm.pas' {EditForm},
  fGridForm in 'Abstract\fGridForm.pas' {GridForm},
  fBottomButtonGridForm in 'Abstract\fBottomButtonGridForm.pas' {BottomButtonGridForm},
  fInnerButtonGridForm in 'Abstract\fInnerButtonGridForm.pas' {InnerButtonGridForm},
  fRightButtonGridForm in 'Abstract\fRightButtonGridForm.pas' {RightButtonGridForm},
  fMasterDetailForm in 'Abstract\fMasterDetailForm.pas' {MasterDetailForm},
  fFilterForm in 'Abstract\fFilterForm.pas' {FilterForm},
  fBevelEditForm in 'Abstract\fBevelEditForm.pas' {BevelEditForm},
  fBevelFilterForm in 'Abstract\fBevelFilterForm.pas' {BevelFilterForm},
  fTreeForm in 'Abstract\fTreeForm.pas' {TreeForm},
  fTreeSplitForm in 'Abstract\fTreeSplitForm.pas' {TreeSplitForm},
  fTreeGridForm in 'Abstract\fTreeGridForm.pas' {TreeGridForm},
  fTreeNomForm in 'Abstract\fTreeNomForm.pas' {TreeNomForm},
  fTreeSelectForm in 'Abstract\fTreeSelectForm.pas' {TreeSelectForm},
  fTreeNodeParamFilterForm in 'fTreeNodeParamFilterForm.pas' {TreeNodeParamFilterForm},
  fProductFilterFloatParam in 'Abstract\fProductFilterFloatParam.pas' {fmProductFilterFloatParam},
  fProductFilterStringParam in 'Abstract\fProductFilterStringParam.pas' {fmProductFilterStringParam},
  fProductParamNomValue in 'Abstract\fProductParamNomValue.pas' {fmProductParamNomValue},
  fLogin in 'fLogin.pas' {fmLogin},
  fDeliveriesFilter in 'fDeliveriesFilter.pas' {fmDeliveriesFilter},
  fDeficitCoverDecision in 'fDeficitCoverDecision.pas' {fmDeficitCoverDecision},
  fProductsTree in 'fProductsTree.pas' {fmProductsTree},
  fDelivery in 'fDelivery.pas' {fmDelivery},
  fGroupDeliveriesFilter in 'fGroupDeliveriesFilter.pas' {fmGroupDeliveriesFilter},
  fDeptsTree in 'fDeptsTree.pas' {fmDeptsTree},
  fDeficitCoverDecisions in 'fDeficitCoverDecisions.pas' {fmDeficitCoverDecisions},
  fDeficitCoverDecisionsFilter in 'fDeficitCoverDecisionsFilter.pas' {fmDeficitCoverDecisionsFilter},
  rDeficitCoverDecisions in 'rDeficitCoverDecisions.pas' {rptDeficitCoverDecisions: TQuickRep},
  rProductDelivery in 'rProductDelivery.pas' {rptProductDelivery: TQuickRep},
  fShipmentTypes in 'fShipmentTypes.pas' {fmShipmentTypes},
  fEmployees in 'fEmployees.pas' {fmEmployees},
  fCountries in 'fCountries.pas' {fmCountries},
  fUsers in 'fUsers.pas' {fmUsers},
  fCustomhouses in 'fCustomhouses.pas' {fmCustomhouses},
  fCountry in 'fCountry.pas' {fmCountry},
  fEmployee in 'fEmployee.pas' {fmEmployee},
  fCustomhouse in 'fCustomhouse.pas' {fmCustomhouse},
  fShipmentType in 'fShipmentType.pas' {fmShipmentType},
  rStoreRequests in 'rStoreRequests.pas' {rptStoreRequests: TQuickRep},
  fStoreDeal in 'fStoreDeal.pas' {fmStoreDeal},
  fSale in 'fSale.pas' {fmSale},
  fStoreQuantitiesFilter in 'fStoreQuantitiesFilter.pas' {fmStoreQuantitiesFilter},
  fBaseFrame in 'Abstract\fBaseFrame.pas' {BaseFrame: TFrame},
  fDBFrame in 'Abstract\fDBFrame.pas' {DBFrame: TFrame},
  fFieldEditFrame in 'Abstract\fFieldEditFrame.pas' {FieldEditFrame: TFrame},
  fStoreDealsFilter in 'fStoreDealsFilter.pas' {fmStoreDealsFilter},
  fPlannedStoreDeals in 'fPlannedStoreDeals.pas' {fmPlannedStoreDeals},
  fPlannedStoreDealsFilter in 'fPlannedStoreDealsFilter.pas' {fmPlannedStoreDealsFilter},
  fSaleShipments in 'fSaleShipments.pas' {fmSaleShipments},
  fSaleShipmentEdit in 'fSaleShipmentEdit.pas' {fmSaleShipmentEdit},
  fQuickSale in 'fQuickSale.pas' {fmQuickSale},
  fDeptsTreeEditor in 'fDeptsTreeEditor.pas' {fmDeptsTreeEditor},
  fDeptsTreeEditorEdit in 'fDeptsTreeEditorEdit.pas' {fmDeptsTreeEditorEdit},
  fSpecifications in 'fSpecifications.pas' {fmSpecifications},
  fSpecificationsFilter in 'fSpecificationsFilter.pas' {fmSpecificationsFilter},
  fPlannedStoreDeal in 'fPlannedStoreDeal.pas' {fmPlannedStoreDeal},
  fCurrencyRates in 'fCurrencyRates.pas' {fmCurrencyRates},
  fVendorProductSignatures in 'fVendorProductSignatures.pas' {fmVendorProductSignatures},
  fVendorProductSignature in 'fVendorProductSignature.pas' {fmVendorProductSignature},
  fTreeNomWithParamsForm in 'Abstract\fTreeNomWithParamsForm.pas' {TreeNomWithParamsForm},
  fTreeNomWithParamsEditForm in 'Abstract\fTreeNomWithParamsEditForm.pas' {TreeNomWithParamsEditForm},
  fProductsTreeEditor in 'fProductsTreeEditor.pas' {fmProductsTreeEditor},
  fProductsTreeEditorEdit in 'fProductsTreeEditorEdit.pas' {fmProductsTreeEditorEdit},
  fParamEdit in 'fParamEdit.pas' {fmParamEdit},
  fCompanies in 'fCompanies.pas' {fmCompanies},
  fCompany in 'fCompany.pas' {fmCompany},
  fMeasures in 'fMeasures.pas' {fmMeasures},
  fMeasure in 'fMeasure.pas' {fmMeasure},
  fTreeNomWithParamsAndPrefixAndSuffixEditForm in 'Abstract\fTreeNomWithParamsAndPrefixAndSuffixEditForm.pas' {TreeNomWithParamsAndPrefixAndSuffixEditForm},
  fPriorities in 'fPriorities.pas' {fmPriorities},
  fPriority in 'fPriority.pas' {fmPriority},
  fNoms in 'fNoms.pas' {fmNoms},
  fNom in 'fNom.pas' {fmNom},
  fCompanyOffice in 'fCompanyOffice.pas' {fmCompanyOffice},
  fCompanyOffices in 'fCompanyOffices.pas' {fmCompanyOffices},
  fBaseSaleForm in 'fBaseSaleForm.pas' {BaseSaleForm},
  fProductionOrder in 'fProductionOrder.pas' {fmProductionOrder},
  fCompanyRepresentatives in 'fCompanyRepresentatives.pas' {fmCompanyRepresentatives},
  fCompanyRepresentative in 'fCompanyRepresentative.pas' {fmCompanyRepresentative},
  fCompanyContacts in 'fCompanyContacts.pas' {fmCompanyContacts},
  fCompanyContact in 'fCompanyContact.pas' {fmCompanyContact},
  fCompanyBankAccounts in 'fCompanyBankAccounts.pas' {fmCompanyBankAccounts},
  fCompanyBankAccount in 'fCompanyBankAccount.pas' {fmCompanyBankAccount},
  fProcessObjectFrame in 'Abstract\fProcessObjectFrame.pas' {ProcessObjectFrame: TFrame},
  fStoreDealProcessObject in 'fStoreDealProcessObject.pas' {frStoreDealProcessObject: TFrame},
  fMLLProcessObject in 'fMLLProcessObject.pas' {frMLLProcessObject: TFrame},
  fDeliveryProcessObject in 'fDeliveryProcessObject.pas' {frDeliveryProcessObject: TFrame},
  fPPProcessObject in 'fPPProcessObject.pas' {frPPProcessObject: TFrame},
  fLanguages in 'fLanguages.pas' {fmLanguages},
  fLanguage in 'fLanguage.pas' {fmLanguage},
  fXModel in 'fXModel.pas' {fmXModel},
  fMLBoundProcessObject in 'fMLBoundProcessObject.pas' {frMLBoundProcessObject: TFrame},
  fProcessBindingFrame in 'Abstract\fProcessBindingFrame.pas' {ProcessBindingFrame: TFrame},
  fStoreDealProcessBinding in 'fStoreDealProcessBinding.pas' {frStoreDealProcessBinding: TFrame},
  fStoreDealInProcessObject in 'fStoreDealInProcessObject.pas' {frStoreDealInProcessObject: TFrame},
  fStoreDealOutProcessObject in 'fStoreDealOutProcessObject.pas' {frStoreDealOutProcessObject: TFrame},
  fCurrencies in 'fCurrencies.pas' {fmCurrencies},
  fCurrency in 'fCurrency.pas' {fmCurrency},
  fSDBindingPlannedSD in 'fSDBindingPlannedSD.pas' {frSDBindingPlannedSD: TFrame},
  fStoreDealIn in 'fStoreDealIn.pas' {fmStoreDealIn},
  fStoreDealOut in 'fStoreDealOut.pas' {fmStoreDealOut},
  fSDBindingWorkProcess in 'fSDBindingWorkProcess.pas' {frSDBindingWorkProcess: TFrame},
  fProductQuantitiesTree in 'fProductQuantitiesTree.pas' {fmProductQuantitiesTree},
  fProductQuantitiesTreeEdit in 'fProductQuantitiesTreeEdit.pas' {fmProductQuantitiesTreeEdit},
  fTreeNomEditorForm in 'Abstract\fTreeNomEditorForm.pas' {TreeNomEditorForm},
  fSaleShipmentProcessObject in 'fSaleShipmentProcessObject.pas' {frSaleShipmentProcessObject: TFrame},
  fConfig in 'fConfig.pas' {fmConfig},
  fAbout in 'fAbout.pas' {fmAbout},
  fTreeNomWithParamsAndPrefixAndSuffixForm in 'Abstract\fTreeNomWithParamsAndPrefixAndSuffixForm.pas' {TreeNomWithParamsAndPrefixAndSuffixForm},
  rCompanies in 'rCompanies.pas' {rptCompanies: TQuickRep},
  rTreeDefault in 'rTreeDefault.pas' {rptTreeDefault: TQuickRep},
  fEmptyFieldEditFrame in 'fEmptyFieldEditFrame.pas' {frEmptyFieldEditFrame: TFrame},
  rStoreQuantities in 'rStoreQuantities.pas' {rptStoreQuantities: TQuickRep},
  rProductQuantitiesTree in 'rProductQuantitiesTree.pas' {rptProductQuantitiesTree: TQuickRep},
  rEmployees in 'rEmployees.pas' {rptEmployees: TQuickRep},
  rPlannedStoreDeals in 'rPlannedStoreDeals.pas' {rptPlannedStoreDeals: TQuickRep},
  rProductionOrder in 'rProductionOrder.pas' {rptProductionOrder: TQuickRep},
  fStoreRequest in 'fStoreRequest.pas' {fmStoreRequest},
  rVIMQuantity in 'rVIMQuantity.pas' {rptVIMQuantity: TQuickRep},
  fStoreRequestMultiEdit in 'fStoreRequestMultiEdit.pas' {fmStoreRequestMultiEdit},
  fGroupSaleLine in 'fGroupSaleLine.pas' {fmGroupSaleLine},
  fStoreRequestItemEdit in 'fStoreRequestItemEdit.pas' {fmStoreRequestItemEdit},
  fStoreRequestsAbstract in 'fStoreRequestsAbstract.pas' {fmStoreRequestsAbstract},
  fStoreRequestsFilter in 'fStoreRequestsFilter.pas' {fmStoreRequestsFilter},
  fStoreRequestTotal in 'fStoreRequestTotal.pas' {fmStoreRequestTotal},
  fQuantityDeficit in 'fQuantityDeficit.pas' {fmQuantityDeficit},
  uColorConsts in 'uColorConsts.pas',
  rGroupSale in 'rGroupSale.pas' {rptGroupSale: TQuickRep},
  fQuantityDeficitFilter in 'fQuantityDeficitFilter.pas' {fmQuantityDeficitFilter},
  rGroupSales in 'rGroupSales.pas' {rptGroupSales: TQuickRep},
  fSaleQuantities in 'fSaleQuantities.pas' {fmSaleQuantities},
  fSaleQuantitiesFilter in 'fSaleQuantitiesFilter.pas' {fmSaleQuantitiesFilter},
  rSaleQuantities in 'rSaleQuantities.pas' {rptSaleQuantities: TQuickRep},
  rSaleQuantitiesByClient in 'rSaleQuantitiesByClient.pas' {rptSaleQuantitiesByClient: TQuickRep},
  rSpecification in 'rSpecification.pas' {rptSpecification: TQuickRep},
  rStoreDeals in 'rStoreDeals.pas' {rptStoreDeals: TQuickRep},
  fPlannedStoreDealIn in 'fPlannedStoreDealIn.pas' {fmPlannedStoreDealIn},
  fPlannedStoreDealOut in 'fPlannedStoreDealOut.pas' {fmPlannedStoreDealOut},
  fSpecificationAndXModelAbstract in 'fSpecificationAndXModelAbstract.pas' {fmSpecificationAndXModelAbstract},
  fSpecification in 'fSpecification.pas' {fmSpecification},
  fSpecDetail in 'fSpecDetail.pas' {fmSpecDetail},
  fSpecMaterial in 'fSpecMaterial.pas' {fmSpecMaterial},
  fInvoices in 'fInvoices.pas' {fmInvoices},
  fInvoicesFilter in 'fInvoicesFilter.pas' {fmInvoicesFilter},
  fInvoice in 'fInvoice.pas' {fmInvoice},
  fInvoiceItem in 'fInvoiceItem.pas' {fmInvoiceItem},
  uPaymentTypes in 'uPaymentTypes.pas',
  uInvoiceTypes in '..\Common\uInvoiceTypes.pas',
  rInvoice in 'rInvoice.pas' {rptInvoice: TQuickRep},
  fInvoiceItemDebitOrCredit in 'fInvoiceItemDebitOrCredit.pas' {fmInvoiceItemDebitOrCredit},
  fVIMQuantity in 'fVIMQuantity.pas' {fmVIMQuantity},
  fVIMQuantityFilter in 'fVIMQuantityFilter.pas' {fmVIMQuantityFilter},
  fSpecModelVariantsCopyTo in 'fSpecModelVariantsCopyTo.pas' {fmSpecModelVariantsCopyTo},
  fSaleExpGroups in 'fSaleExpGroups.pas' {fmSaleExpGroups},
  fDeficitCoverDecisionProcessObject in 'fDeficitCoverDecisionProcessObject.pas' {frDeficitCoverDecisionProcessObject: TFrame},
  fSingleExpsFilter in 'fSingleExpsFilter.pas' {fmSingleExpsFilter},
  rInvoices in 'rInvoices.pas' {rptInvoices: TQuickRep},
  rSpecifications in 'rSpecifications.pas' {rptSpecifications: TQuickRep},
  fSpecificationCreateLikeFilter in 'fSpecificationCreateLikeFilter.pas' {fmSpecificationCreateLikeFilter},
  fSaleExpGroupsFilter in 'fSaleExpGroupsFilter.pas' {fmSaleExpGroupsFilter},
  fDaysOff in 'fDaysOff.pas' {fmDaysOff},
  fSpecModelVariantStageEdit in 'fSpecModelVariantStageEdit.pas' {fmSpecModelVariantStageEdit},
  fSpecModelVariantEdit in 'fSpecModelVariantEdit.pas' {fmSpecModelVariantEdit},
  fDeliveries in 'fDeliveries.pas' {fmDeliveries},
  fXModelsFilter in 'fXModelsFilter.pas' {fmXModelsFilter},
  fXModels in 'fXModels.pas' {fmXModels},
  rGroupDeliveries in 'rGroupDeliveries.pas' {rptGroupDeliveries: TQuickRep},
  rDeliveries in 'rDeliveries.pas' {rptDeliveries: TQuickRep},
  fTreeNodeParamsFrame in 'fTreeNodeParamsFrame.pas' {frTreeNodeParams: TFrame},
  fXModelDetail in 'fXModelDetail.pas' {fmXModelDetail},
  fXModelMaterial in 'fXModelMaterial.pas' {fmXModelMaterial},
  fUncoveredPSDSingle in 'fUncoveredPSDSingle.pas' {fmUncoveredPSDSingle},
  fUncoveredPSDSingleFilter in 'fUncoveredPSDSingleFilter.pas' {fmUncoveredPSDSingleFilter},
  rUncoveredPSDSingle in 'rUncoveredPSDSingle.pas' {rptUncoveredPSDSingle: TQuickRep},
  fUncoveredModels in 'fUncoveredModels.pas' {fmUncoveredModels},
  fUncoveredModelsFilter in 'fUncoveredModelsFilter.pas' {fmUncoveredModelsFilter},
  rUncoveredModels in 'rUncoveredModels.pas' {rptUncoveredModels: TQuickRep},
  rSaleExpGroups in 'rSaleExpGroups.pas' {rptSaleExpGroups: TQuickRep},
  rSingleExps in 'rSingleExps.pas' {rptSingleExps: TQuickRep},
  fAnimatedSplash in 'Abstract\fAnimatedSplash.pas' {fmAnimatedSplash},
  fXModelStageEdit in 'fXModelStageEdit.pas' {fmXModelStageEdit},
  fXModelFork in 'fXModelFork.pas' {fmXModelFork},
  fMaterialListLineChange in 'fMaterialListLineChange.pas' {fmMaterialListLineChange},
  fModelMovementsOverview in 'fModelMovementsOverview.pas' {fmModelMovementsOverview},
  fModelMovementsOverviewFilter in 'fModelMovementsOverviewFilter.pas' {fmModelMovementsOverviewFilter},
  rModelMovementsOverview in 'rModelMovementsOverview.pas' {rptModelMovementsOverview: TQuickRep},
  fXModelInsertSpecModelVariantNo in 'fXModelInsertSpecModelVariantNo.pas' {fmXModelInsertSpecModelVariantNo},
  fMaterialListLineMultiChange in 'fMaterialListLineMultiChange.pas' {fmMaterialListLineMultiChange},
  fConfigUser in 'fConfigUser.pas' {fmConfigUser},
  fSpecModelVariantTaskEdit in 'fSpecModelVariantTaskEdit.pas' {fmSpecModelVariantTaskEdit},
  fSpecAndXModelTaskDeptEdit in 'fSpecAndXModelTaskDeptEdit.pas' {fmSpecAndXModelTaskDeptEdit},
  fXModelTaskEdit in 'fXModelTaskEdit.pas' {fmXModelTaskEdit},
  fModelStatusAbstract in 'fModelStatusAbstract.pas' {fmModelStatusAbstract},
  rTasks in 'rTasks.pas' {rptTasks: TQuickRep},
  rSpecModelTasks in 'rSpecModelTasks.pas' {rptSpecModelTasks: TQuickRep},
  fSDBindingSimpleDelivery in 'fSDBindingSimpleDelivery.pas' {frSDBindingSimpleDelivery: TFrame},
  rXModelTasks in 'rXModelTasks.pas' {rptXModelTasks: TQuickRep},
  rXModels in 'rXModels.pas' {rptXModels: TQuickRep},
  uOpenVIMConsts in 'uOpenVIMConsts.pas',
  fOtherStoreRequests in 'fOtherStoreRequests.pas' {fmOtherStoreRequests},
  fStoreRequests in 'fStoreRequests.pas' {fmStoreRequests},
  fUnfinishedMfg in 'fUnfinishedMfg.pas' {fmUnfinishedMfg},
  fStoreRequestMultiEditFilter in 'fStoreRequestMultiEditFilter.pas' {fmStoreRequestMultiEditFilter},
  fStoreQuantities in 'fStoreQuantities.pas' {fmStoreQuantities},
  fUnfinishedMfgFilter in 'fUnfinishedMfgFilter.pas' {fmUnfinishedMfgFilter},
  rUnfinishedMfg in 'rUnfinishedMfg.pas' {rptUnfinishedMfg: TQuickRep},
  fSelectSpecReplaceProducts in 'fSelectSpecReplaceProducts.pas' {fmSelectSpecReplaceProducts},
  fDocItemTypes in 'fDocItemTypes.pas' {fmDocItemTypes},
  uDocClientUtils in 'uDocClientUtils.pas',
  fTreeNodeParamsTreeFilterForm in 'Abstract\fTreeNodeParamsTreeFilterForm.pas' {TreeNodeParamsTreeFilterForm},
  fProductParamsFilter in 'fProductParamsFilter.pas' {fmProductParamsFilter},
  fModelChanges in 'fModelChanges.pas' {fmModelChanges},
  fUserActivities in 'fUserActivities.pas' {fmUserActivities},
  fUserGroups in 'fUserGroups.pas' {fmUserGroups},
  fUserGroupsEdit in 'fUserGroupsEdit.pas' {fmUserGroupsEdit},
  fUserGroupActivities in 'fUserGroupActivities.pas' {fmUserGroupActivities},
  fProfession in 'fProfession.pas' {fmProfession},
  fTeams in 'fTeams.pas' {fmTeams},
  fDualGridForm in 'Abstract\fDualGridForm.pas' {DualGridForm},
  fTeam in 'fTeam.pas' {fmTeam},
  fMonthTeams in 'fMonthTeams.pas' {fmMonthTeams},
  fMonthTeam in 'fMonthTeam.pas' {fmMonthTeam},
  fMonthTeamEmployee in 'fMonthTeamEmployee.pas' {fmMonthTeamEmployee},
  fSMVSOperationEdit in 'fSMVSOperationEdit.pas' {fmSMVSOperationEdit},
  fMLMSOperationEdit in 'fMLMSOperationEdit.pas' {fmMLMSOperationEdit},
  fMonth in 'fMonth.pas' {frMonth: TFrame},
  fSQL in 'fSQL.pas' {fmSQL},
  fSpecificationPrintOptions in 'fSpecificationPrintOptions.pas' {fmSpecificationPrintOptions},
  dDocClient in 'dDocClient.pas' {dmDocClient: TDataModule},
  fSaleTypes in 'fSaleTypes.pas' {fmSaleTypes},
  fSaleType in 'fSaleType.pas' {fmSaleType},
  fOutStoreDealsExport in 'fOutStoreDealsExport.pas' {fmOutStoreDealsExport},
  fTimeline in 'fTimeline.pas' {frTimeline: TFrame},
  uExcelExport in 'uExcelExport.pas',
  fDeptTypes in 'fDeptTypes.pas' {fmDeptTypes},
  fDeptType in 'fDeptType.pas' {fmDeptType},
  rSpecAndXModelRecursivePrintAbstract in 'rSpecAndXModelRecursivePrintAbstract.pas' {rptSpecAndXModelRecursivePrintAbstract: TQuickRep},
  rSpecRecursivePrint in 'rSpecRecursivePrint.pas' {rptSpecRecursivePrint: TQuickRep},
  fSpecAndXModelRecursivePrintOptions in 'fSpecAndXModelRecursivePrintOptions.pas' {fmSpecAndXModelRecursivePrintOptions},
  rXModelRecursivePrint in 'rXModelRecursivePrint.pas' {rptXModelRecursivePrint: TQuickRep},
  fParamProductFilter in 'fParamProductFilter.pas' {frParamProductFilter: TFrame},
  fProductEdit in 'fProductEdit.pas' {fmProductEdit},
  fDeptEdit in 'fDeptEdit.pas' {fmDeptEdit},
  fParamProductFilterParamEdit in 'fParamProductFilterParamEdit.pas' {fmParamProductFilterParamEdit},
  fStructurePartNeeds in 'fStructurePartNeeds.pas' {fmStructurePartNeeds},
  fStructurePartNeedsFilter in 'fStructurePartNeedsFilter.pas' {fmStructurePartNeedsFilter},
  fStructurePartNeedsByResultProduct in 'fStructurePartNeedsByResultProduct.pas' {fmStructurePartNeedsByResultProduct},
  fStructurePartNeedsByUpperLevelStructurePart in 'fStructurePartNeedsByUpperLevelStructurePart.pas' {fmStructurePartNeedsByUpperLevelStructurePart},
  fStructurePartNeedsBySale in 'fStructurePartNeedsBySale.pas' {fmStructurePartNeedsBySale},
  fProductionProductsTree in 'fProductionProductsTree.pas' {fmProductionProductsTree},
  fProductionProduct in 'fProductionProduct.pas' {fmProductionProduct},
  fProductLocations in 'fProductLocations.pas' {fmProductLocations},
  fProductLocationEdit in 'fProductLocationEdit.pas' {fmProductLocationEdit},
  fResultProductNeeds in 'fResultProductNeeds.pas' {fmResultProductNeeds},
  fResultProductNeedsBySale in 'fResultProductNeedsBySale.pas' {fmResultProductNeedsBySale},
  uClientTypes in 'uClientTypes.pas',
  fDocItems in 'fDocItems.pas' {fmDocItems},
  fResultProductNeedsFilter in 'fResultProductNeedsFilter.pas' {fmResultProductNeedsFilter},
  fDocItemsEdit in 'fDocItemsEdit.pas' {fmDocItemsEdit},
  fCompanyFilter in 'fCompanyFilter.pas' {frCompanyFilter: TFrame},
  fProductMinQuantities in 'fProductMinQuantities.pas' {fmProductMinQuantities},
  fProductMinQuantityEdit in 'fProductMinQuantityEdit.pas' {fmProductMinQuantityEdit},
  fNeedsCommonHeader in 'fNeedsCommonHeader.pas' {frNeedsCommonHeader: TFrame},
  rResultProductNeeds in 'rResultProductNeeds.pas' {rptResultProductNeeds: TQuickRep},
  rResultProductNeedsBySale in 'rResultProductNeedsBySale.pas' {rptResultProductNeedsBySale: TQuickRep},
  rNeedsAbstract in 'rNeedsAbstract.pas' {rptNeedsAbstract: TQuickRep},
  rStructurePartNeedsBySale in 'rStructurePartNeedsBySale.pas' {rptStructurePartNeedsBySale: TQuickRep},
  rStructurePartNeeds in 'rStructurePartNeeds.pas' {rptStructurePartNeeds: TQuickRep},
  rStructurePartNeedsByResultProduct in 'rStructurePartNeedsByResultProduct.pas' {rptStructurePartNeedsByResultProduct: TQuickRep},
  rStructurePartNeedsByUpperLevelStructurePart in 'rStructurePartNeedsByUpperLevelStructurePart.pas' {rptStructurePartNeedsByUpperLevelStructurePart: TQuickRep},
  fOperationMovement in 'fOperationMovement.pas' {fmOperationMovement},
  fShipmentNeededMaterials in 'fShipmentNeededMaterials.pas' {fmShipmentNeededMaterials},
  fOneMLMSOperations in 'fOneMLMSOperations.pas' {fmOneMLMSOperations},
  fMLMSOperationVariants in 'fMLMSOperationVariants.pas' {fmMLMSOperationVariants},
  fMLMSOperationSetup in 'fMLMSOperationSetup.pas' {fmMLMSOperationSetup},
  uCompanyClientUtils in 'uCompanyClientUtils.pas',
  uTreeClientUtils in 'uTreeClientUtils.pas',
  fUserEffectiveActivities in 'fUserEffectiveActivities.pas' {fmUserEffectiveActivities},
  fProductionOrders in 'fProductionOrders.pas' {fmProductionOrders},
  fProductionOrdersFilter in 'fProductionOrdersFilter.pas' {fmProductionOrdersFilter},
  uModelUtils in 'uModelUtils.pas',
  uProductionOrderTypes in 'uProductionOrderTypes.pas',
  fMLMSOperation in 'fMLMSOperation.pas' {frMLMSOperation: TFrame},
  rProductionOrders in 'rProductionOrders.pas' {rptProductionOrders: TQuickRep},
  fOperationMovements in 'fOperationMovements.pas' {fmOperationMovements},
  fOperationMovementsFilter in 'fOperationMovementsFilter.pas' {fmOperationMovementsFilter},
  fOperationalTasks in 'fOperationalTasks.pas' {fmOperationalTasks},
  fOperationalTasksFilter in 'fOperationalTasksFilter.pas' {fmOperationalTasksFilter},
  rStructureSpecification in 'rStructureSpecification.pas' {rptStructureSpecification: TQuickRep},
  rDepts in 'rDepts.pas' {rptDepts: TQuickRep},
  rBaseOperationsReport in 'rBaseOperationsReport.pas' {BaseOperationsReport: TQuickRep},
  rSpecAndXModelOperations in 'rSpecAndXModelOperations.pas' {rptSpecAndXModelOperations: TQuickRep},
  rSpecOperations in 'rSpecOperations.pas' {rptSpecOperations: TQuickRep},
  rBaseOperationMovementReport in 'rBaseOperationMovementReport.pas' {BaseOperationMovementReport: TQuickRep},
  rOperationMovementToOperation in 'rOperationMovementToOperation.pas' {rptOperationMovementToOperation: TQuickRep},
  rOperationMovementToSpecControl in 'rOperationMovementToSpecControl.pas' {rptOperationMovementToSpecControl: TQuickRep},
  rXModelOperations in 'rXModelOperations.pas' {rptXModelOperations: TQuickRep},
  rOperationalTasks in 'rOperationalTasks.pas' {rptOperationalTasks: TQuickRep},
  rOperationMovementToWaste in 'rOperationMovementToWaste.pas' {rptOperationMovementToWaste: TQuickRep},
  rOperationalMovements in 'rOperationalMovements.pas' {rptOperationalMovements: TQuickRep},
  fMLMSOperationVariant in 'fMLMSOperationVariant.pas' {fmMLMSOperationVariant},
  fOperationInputOutput in 'fOperationInputOutput.pas' {fmOperationInputOutput},
  rOperationInputOutput in 'rOperationInputOutput.pas' {rptOperationInputOutput: TQuickRep},
  fMaterialListLineStoreMultiChange in 'fMaterialListLineStoreMultiChange.pas' {fmMaterialListLineStoreMultiChange},
  fCurrentDept in 'fCurrentDept.pas' {fmCurrentDept},
  fBaseGroups in 'fBaseGroups.pas' {fmBaseGroups},
  fFilterVariant in 'fFilterVariant.pas' {fmFilterVariant},
  fTreeNodeFilter in 'Abstract\fTreeNodeFilter.pas' {frTreeNodeFilter: TFrame},
  fProductFilter in 'fProductFilter.pas' {frProductFilter: TFrame},
  fDeptDetailFlow in 'fDeptDetailFlow.pas' {fmDeptDetailFlow},
  fDeptDetailFlowFilter in 'fDeptDetailFlowFilter.pas' {fmDeptDetailFlowFilter},
  fDeptFilter in 'fDeptFilter.pas' {frDeptFilter: TFrame},
  fBaseGroupsFilter in 'fBaseGroupsFilter.pas' {fmBaseGroupsFilter},
  fBaseGroup in 'fBaseGroup.pas' {fmBaseGroup},
  fFilterVariantSysRoles in 'fFilterVariantSysRoles.pas' {fmFilterVariantSysRoles},
  uClientConsts in 'uClientConsts.pas',
  fDualGridFrame in 'Abstract\fDualGridFrame.pas' {DualGridFrame: TFrame},
  fTeamsFilter in 'fTeamsFilter.pas' {fmTeamsFilter},
  fEmployeeEarnings in 'fEmployeeEarnings.pas' {fmEmployeeEarnings},
  fEmployeeEarningsFilter in 'fEmployeeEarningsFilter.pas' {fmEmployeeEarningsFilter},
  rEmployeeEarnings in 'rEmployeeEarnings.pas' {rptEmployeeEarnings: TQuickRep},
  fMonthTeamsFilter in 'fMonthTeamsFilter.pas' {fmMonthTeamsFilter},
  fEarningModifiers in 'fEarningModifiers.pas' {fmEarningModifiers},
  fEarningModifier in 'fEarningModifier.pas' {fmEarningModifier},
  fEarningModifiersFilter in 'fEarningModifiersFilter.pas' {fmEarningModifiersFilter},
  fOccupation in 'fOccupation.pas' {fmOccupation},
  fEducations in 'fEducations.pas' {fmEducations},
  fEducation in 'fEducation.pas' {fmEducation},
  fShifts in 'fShifts.pas' {fmShifts},
  fShift in 'fShift.pas' {fmShift},
  fWorkHours in 'fWorkHours.pas' {fmWorkHours},
  fWorkHoursFilter in 'fWorkHoursFilter.pas' {fmWorkHoursFilter},
  fOccupationProfessionsDepts in 'fOccupationProfessionsDepts.pas' {fmOccupationProfessionsDepts},
  fOccupationProfessionsDept in 'fOccupationProfessionsDept.pas' {fmOccupationProfessionsDept},
  rWorkHours in 'rWorkHours.pas' {rptWorkHours: TQuickRep},
  fEmployeeDisciplineEvents in 'fEmployeeDisciplineEvents.pas' {frEmployeeDisciplineEvents: TFrame},
  fEmployeeDisciplineEvent in 'fEmployeeDisciplineEvent.pas' {fmEmployeeDisciplineEvent},
  fColor in 'fColor.pas' {frColor: TFrame},
  fOccupationsAndEmployees in 'fOccupationsAndEmployees.pas' {fmOccupationsAndEmployees},
  fOccupationsAndEmployeesFilter in 'fOccupationsAndEmployeesFilter.pas' {fmOccupationsAndEmployeesFilter},
  fOccupationAndEmployee in 'fOccupationAndEmployee.pas' {fmOccupationAndEmployee},
  fXModelAddFork in 'fXModelAddFork.pas' {fmXModelAddFork},
  fModelStatus in 'fModelStatus.pas' {fmModelStatus},
  fCapacityGraph in 'fCapacityGraph.pas' {fmCapacityGraph},
  fCapacityAbstractFilter in 'fCapacityAbstractFilter.pas' {fmCapacityAbstractFilter},
  fModelCapacityStatus in 'fModelCapacityStatus.pas' {fmModelCapacityStatus},
  fCapacityTable in 'fCapacityTable.pas' {fmCapacityTable},
  uCapacity in '..\Common\uCapacity.pas',
  fProfessionKinds in 'fProfessionKinds.pas' {fmProfessionKinds},
  fProfessionKind in 'fProfessionKind.pas' {fmProfessionKind},
  fCapacityGraphFilter in 'fCapacityGraphFilter.pas' {fmCapacityGraphFilter},
  fCapacityTableFilter in 'fCapacityTableFilter.pas' {fmCapacityTableFilter},
  fSelectModelTask in 'fSelectModelTask.pas' {fmSelectModelTask},
  uGraphUtils in 'uGraphUtils.pas',
  rCapacityGraph in 'rCapacityGraph.pas' {rptCapacityGraph: TQuickRep},
  uCapacityClient in 'uCapacityClient.pas',
  fOccupationWorkDeptPriorities in 'fOccupationWorkDeptPriorities.pas' {fmOccupationWorkDeptPriorities},
  fOccupationWorkDeptPriority in 'fOccupationWorkDeptPriority.pas' {fmOccupationWorkDeptPriority},
  rOccupationsAndEmployees in 'rOccupationsAndEmployees.pas' {rptOccupationsAndEmployees: TQuickRep},
  rMonthTeams in 'rMonthTeams.pas' {rptMonthTeams: TQuickRep},
  rOccupationAndEmployee in 'rOccupationAndEmployee.pas' {rptOccupationAndEmployee: TQuickRep},
  rMLMSOperationSetup in 'rMLMSOperationSetup.pas' {rptMLMSOperationSetup: TQuickRep},
  uMessageDecodingUtils in 'uMessageDecodingUtils.pas',
  fTreeNodeFieldEditFrame in 'fTreeNodeFieldEditFrame.pas' {TreeNodeFieldEditFrame: TFrame},
  fDeptFieldEditFrame in 'fDeptFieldEditFrame.pas' {frDeptFieldEditFrame: TFrame},
  fProductFieldEditFrame in 'fProductFieldEditFrame.pas' {frProductFieldEditFrame: TFrame},
  fDeptFieldEditFrameBald in 'fDeptFieldEditFrameBald.pas' {frDeptFieldEditFrameBald: TFrame},
  rWorkHoursDetail in 'rWorkHoursDetail.pas' {rptWorkHoursDetail: TQuickRep},
  fProductFieldEditFrameBald in 'fProductFieldEditFrameBald.pas' {frProductFieldEditFrameBald: TFrame},
  uServerMessageTexts in 'uServerMessageTexts.pas',
  uServerMessageIds in '..\Common\uServerMessageIds.pas',
  uMessageUtils in '..\Common\uMessageUtils.pas',
  fEmployeesFilter in 'fEmployeesFilter.pas' {fmEmployeesFilter},
  uClientPeriods in 'uClientPeriods.pas',
  uClientMaterialListLineChanges in 'uClientMaterialListLineChanges.pas',
  uEarningTypes in '..\Common\uEarningTypes.pas',
  uClientEarningTypes in 'uClientEarningTypes.pas',
  rInvoicesWithoutDiscount in 'rInvoicesWithoutDiscount.pas' {rptInvoicesWithoutDiscount: TQuickRep},
  fEmployeeFieldEditFrame in 'fEmployeeFieldEditFrame.pas' {frEmployeeFieldEditFrame: TFrame},
  uOperationKinds in 'uOperationKinds.pas',
  fBudgetOrder in 'fBudgetOrder.pas' {fmBudgetOrder},
  fDateIntervalFrame in 'fDateIntervalFrame.pas' {frDateIntervalFrame: TFrame},
  fDateIntervalEdit in 'fDateIntervalEdit.pas' {fmDateIntervalEdit},
  fBudgetOrders in 'fBudgetOrders.pas' {fmBudgetOrders},
  fBudgetOrderItem in 'fBudgetOrderItem.pas' {fmBudgetOrderItem},
  uDocUtils in '..\Common\uDocUtils.pas',
  uBudgetClientUtils in 'uBudgetClientUtils.pas',
  fBudgetOrdersFilter in 'fBudgetOrdersFilter.pas' {fmBudgetOrdersFilter},
  fDeptPeriods in 'fDeptPeriods.pas' {fmDeptPeriods},
  fDeptPeriod in 'fDeptPeriod.pas' {fmDeptPeriod},
  fBaseInvestedValueFilter in 'fBaseInvestedValueFilter.pas' {BaseInvestedValueFilter},
  fSpecInvestedValueFilter in 'fSpecInvestedValueFilter.pas' {fmSpecInvestedValueFilter},
  fXModelInvestedValueFilter in 'fXModelInvestedValueFilter.pas' {fmXModelInvestedValueFilter},
  fDocItemTemplates in 'fDocItemTemplates.pas' {fmDocItemTemplates},
  fDocItemTemplate in 'fDocItemTemplate.pas' {fmDocItemTemplate},
  fBPOIProcessObject in 'fBPOIProcessObject.pas' {frBPOIProcessObject: TFrame},
  fModelsInvestedValues in 'fModelsInvestedValues.pas' {fmModelsInvestedValues},
  fModelsInvestedValuesFilter in 'fModelsInvestedValuesFilter.pas' {fmModelsInvestedValuesFilter},
  fModelsInvestedValuesIVFilter in 'fModelsInvestedValuesIVFilter.pas' {fmModelsInvestedValuesIVFilter},
  rModelsInvestedValues in 'rModelsInvestedValues.pas' {rptModelsInvestedValues: TQuickRep},
  rBudgetOrders in 'rBudgetOrders.pas' {rptBudgetOrders: TQuickRep},
  rBudgetOrdersDetail in 'rBudgetOrdersDetail.pas' {rptBudgetOrdersDetail: TQuickRep},
  uRTFUtils in 'uRTFUtils.pas',
  fDocItemViewGenerators in 'fDocItemViewGenerators.pas' {fmDocItemViewGenerators},
  fDocItemViewGenerator in 'fDocItemViewGenerator.pas' {fmDocItemViewGenerator},
  fExecuteServers in 'fExecuteServers.pas' {fmExecuteServers},
  fExecuteServer in 'fExecuteServer.pas' {fmExecuteServer},
  fBudget in 'fBudget.pas' {fmBudget},
  fSelectDocItemTemplate in 'fSelectDocItemTemplate.pas' {fmSelectDocItemTemplate},
  fFileExtensions in 'fFileExtensions.pas' {fmFileExtensions},
  fFileExtension in 'fFileExtension.pas' {fmFileExtension},
  fExecFile in 'fExecFile.pas' {fmExecFile},
  fDocItemType in 'fDocItemType.pas' {fmDocItemType},
  fBudgetFilter in 'fBudgetFilter.pas' {fmBudgetFilter},
  rDeptDetailFlow in 'rDeptDetailFlow.pas' {rptDeptDetailFlow: TQuickRep},
  rDeptDetailFlowDetails in 'rDeptDetailFlowDetails.pas' {rptDeptDetailFlowDetails: TQuickRep},
  fDateUnitsIntervalEditFrame in 'fDateUnitsIntervalEditFrame.pas' {frDateUnitsIntervalEditFrame: TFrame},
  fSpecAndXModelUnapproveAbstract in 'fSpecAndXModelUnapproveAbstract.pas' {fmSpecAndXModelUnapproveAbstract},
  fSpecUnapprove in 'fSpecUnapprove.pas' {fmSpecUnapprove},
  fXModelUnapprove in 'fXModelUnapprove.pas' {fmXModelUnapprove},
  fPriorityIntervalEditFrame in 'fPriorityIntervalEditFrame.pas' {frPriorityIntervalEditFrame: TFrame},
  fSpecAndXModelDocStatusAbstract in 'fSpecAndXModelDocStatusAbstract.pas' {fmSpecAndXModelDocStatusAbstract},
  fSpecDocStatus in 'fSpecDocStatus.pas' {fmSpecDocStatus},
  fXModelDocStatus in 'fXModelDocStatus.pas' {fmXModelDocStatus},
  rBudget in 'rBudget.pas' {rptBudget: TQuickRep},
  fDoc in 'fDoc.pas' {frDoc: TFrame},
  fDocEmptinessRequirement in 'fDocEmptinessRequirement.pas' {fmDocEmptinessRequirement},
  fCustomMenuItems in 'fCustomMenuItems.pas' {fmCustomMenuItems},
  fCustomMenuItem in 'fCustomMenuItem.pas' {fmCustomMenuItem},
  fDateFieldEditFrame in 'fDateFieldEditFrame.pas' {frDateFieldEditFrame: TFrame},
  rSpecAndXModelDocStatusAbstract in 'rSpecAndXModelDocStatusAbstract.pas' {rptSpecAndXModelDocStatusAbstract: TQuickRep},
  rSpecDocStatusLines in 'rSpecDocStatusLines.pas' {rptSpecDocStatusLines: TQuickRep},
  rXModelDocStatusLines in 'rXModelDocStatusLines.pas' {rptXModelDocStatusLines: TQuickRep},
  rSpecAndXModelDocStatusModelAbstract in 'rSpecAndXModelDocStatusModelAbstract.pas' {rptSpecAndXModelDocStatusModelAbstract: TQuickRep},
  rSpecDocStatusModel in 'rSpecDocStatusModel.pas' {rptSpecDocStatusModel: TQuickRep},
  rXModelDocStatusModel in 'rXModelDocStatusModel.pas' {rptXModelDocStatusModel: TQuickRep},
  fCompaniesFilter in 'fCompaniesFilter.pas' {fmCompaniesFilter},
  fPartnerFieldEditFrame in 'fPartnerFieldEditFrame.pas' {frPartnerFieldEditFrame: TFrame},
  rOccupation in 'rOccupation.pas' {rptOccupation: TQuickRep},
  fProductFieldEditFrameLabeled in 'fProductFieldEditFrameLabeled.pas' {frProductFieldEditFrameLabeled: TFrame},
  fDeptFieldEditFrameLabeled in 'fDeptFieldEditFrameLabeled.pas' {frDeptFieldEditFrameLabeled: TFrame},
  fEmployeeFieldEditFrameBald in 'fEmployeeFieldEditFrameBald.pas' {frEmployeeFieldEditFrameBald: TFrame},
  fEmployeeFieldEditFrameLabeled in 'fEmployeeFieldEditFrameLabeled.pas' {frEmployeeFieldEditFrameLabeled: TFrame},
  uDeliveryUtils in 'uDeliveryUtils.pas',
  fShiftRegimes in 'fShiftRegimes.pas' {fmShiftRegimes},
  fShiftRegime in 'fShiftRegime.pas' {fmShiftRegime},
  fPartnerFieldEditFrameBald in 'fPartnerFieldEditFrameBald.pas' {frPartnerFieldEditFrameBald: TFrame},
  fPartnerFieldEditFrameLabeled in 'fPartnerFieldEditFrameLabeled.pas' {frPartnerFieldEditFrameLabeled: TFrame},
  fShiftTimedRegime in 'fShiftTimedRegime.pas' {fmShiftTimedRegime},
  fShiftCycle in 'fShiftCycle.pas' {fmShiftCycle},
  fCraftTypes in 'fCraftTypes.pas' {fmCraftTypes},
  fCraftType in 'fCraftType.pas' {fmCraftType},
  fCrafts in 'fCrafts.pas' {fmCrafts},
  fCraft in 'fCraft.pas' {fmCraft},
  fCommonGroups in 'fCommonGroups.pas' {fmCommonGroups},
  fCommonGroupsFilter in 'fCommonGroupsFilter.pas' {fmCommonGroupsFilter},
  fNotes in 'fNotes.pas' {fmNotes},
  fStatusAbstract in 'fStatusAbstract.pas' {frStatusAbstract: TFrame},
  fRightFlatButtonGridForm in 'Abstract\fRightFlatButtonGridForm.pas' {RightFlatButtonGridForm},
  fCompanyStatuses in 'fCompanyStatuses.pas' {fmCompanyStatuses},
  fCompanyStatusForm in 'fCompanyStatusForm.pas' {fmCompanyStatus},
  fShiftRegimesFilter in 'fShiftRegimesFilter.pas' {fmShiftRegimesFilter},
  fPersonCraft in 'fPersonCraft.pas' {fmPersonCraft},
  fCraftEditFrame in 'fCraftEditFrame.pas' {frCraftEditFrame: TFrame},
  fStageLevelTasks in 'fStageLevelTasks.pas' {fmStageLevelTasks},
  fStageLevelTasksFilter in 'fStageLevelTasksFilter.pas' {fmStageLevelTasksFilter},
  fStageInputOutput in 'fStageInputOutput.pas' {fmStageInputOutput},
  rUncoveredModelDetails in 'rUncoveredModelDetails.pas' {rptUncoveredModelDetails: TQuickRep},
  rStageLevelTasks in 'rStageLevelTasks.pas' {rptStageLevelTasks: TQuickRep},
  rStageInputOutput in 'rStageInputOutput.pas' {rptStageInputOutput: TQuickRep},
  fWorkPriorities in 'fWorkPriorities.pas' {fmWorkPriorities},
  fWorkPriority in 'fWorkPriority.pas' {fmWorkPriority},
  fEngineeringOrderTypes in 'fEngineeringOrderTypes.pas' {fmEngineeringOrderTypes},
  fEngineeringOrderType in 'fEngineeringOrderType.pas' {fmEngineeringOrderType},
  fEngineeringOrder in 'fEngineeringOrder.pas' {fmEngineeringOrder},
  fEngineeringOrders in 'fEngineeringOrders.pas' {fmEngineeringOrders},
  fEngineeringOrdersFilter in 'fEngineeringOrdersFilter.pas' {fmEngineeringOrdersFilter},
  rEngineeringOrders in 'rEngineeringOrders.pas' {rptEngineeringOrders: TQuickRep},
  fOccupationShifts in 'fOccupationShifts.pas' {fmOccupationShifts},
  fOccupationShift in 'fOccupationShift.pas' {fmOccupationShift},
  fShiftCycleBreaks in 'fShiftCycleBreaks.pas' {fmShiftCycleBreaks},
  fShiftCycleBreak in 'fShiftCycleBreak.pas' {fmShiftCycleBreak},
  fBOIOrders in 'fBOIOrders.pas' {fmBOIOrders},
  fBOIProductOrders in 'fBOIProductOrders.pas' {fmBOIProductOrders},
  fBOICompanyOrders in 'fBOICompanyOrders.pas' {fmBOICompanyOrders},
  fBOIWasteOrders in 'fBOIWasteOrders.pas' {fmBOIWasteOrders},
  fBOIOrdersFilter in 'fBOIOrdersFilter.pas' {fmBOIOrdersFilter},
  fBOIProductOrdersFilter in 'fBOIProductOrdersFilter.pas' {fmBOIProductOrdersFilter},
  fBOICompanyOrdersFilter in 'fBOICompanyOrdersFilter.pas' {fmBOICompanyOrdersFilter},
  fBOIWasteOrdersFilter in 'fBOIWasteOrdersFilter.pas' {fmBOIWasteOrdersFilter},
  fBOIOrder in 'fBOIOrder.pas' {fmBOIOrder},
  fBOIProductOrder in 'fBOIProductOrder.pas' {fmBOIProductOrder},
  fBOICompanyOrder in 'fBOICompanyOrder.pas' {fmBOICompanyOrder},
  fBOIWasteOrder in 'fBOIWasteOrder.pas' {fmBOIWasteOrder},
  rBudgetOrder in 'rBudgetOrder.pas' {rptBudgetOrder: TQuickRep},
  rBOIOrders in 'rBOIOrders.pas' {rptBOIOrders: TQuickRep},
  rBOIOrdersDetail in 'rBOIOrdersDetail.pas' {rptBOIOrdersDetail: TQuickRep},
  rBOICompanyOrdersDetail in 'rBOICompanyOrdersDetail.pas' {rptBOICompanyOrdersDetail: TQuickRep},
  rBOIProductOrdersDetail in 'rBOIProductOrdersDetail.pas' {rptBOIProductOrdersDetail: TQuickRep},
  rBOIWasteOrdersDetail in 'rBOIWasteOrdersDetail.pas' {rptBOIWasteOrdersDetail: TQuickRep},
  rBOIProductOrdersDetailReal in 'rBOIProductOrdersDetailReal.pas' {rptBOIProductOrdersDetailReal: TQuickRep},
  fSaleOrderProcessObject in 'fSaleOrderProcessObject.pas' {frSaleOrderProcessObject: TFrame},
  fEmployeeDateAvailability in 'fEmployeeDateAvailability.pas' {fmEmployeeDateAvailability},
  fEmployeeDateAvailabilityMovements in 'fEmployeeDateAvailabilityMovements.pas' {fmEmployeeDateAvailabilityMovements},
  fEmployeeDateAvailabilityMovement in 'fEmployeeDateAvailabilityMovement.pas' {fmEmployeeDateAvailabilityMovement},
  fEmployeeDayAbsenceReasons in 'fEmployeeDayAbsenceReasons.pas' {fmEmployeeDayAbsenceReasons},
  fEmployeeDayAbsenceDocType in 'fEmployeeDayAbsenceDocType.pas' {fmEmployeeDayAbsenceDocType},
  fEmployeeHourAvailabilityModifierReasons in 'fEmployeeHourAvailabilityModifierReasons.pas' {fmEmployeeHourAvailabilityModifierReasons},
  fEmployeeHourAvailabilityModifierReason in 'fEmployeeHourAvailabilityModifierReason.pas' {fmEmployeeHourAvailabilityModifierReason},
  fEmployeeDateAvailabilityModifiers in 'fEmployeeDateAvailabilityModifiers.pas' {fmEmployeeDateAvailabilityModifiers},
  fEmployeeDateAvailabilityModifier in 'fEmployeeDateAvailabilityModifier.pas' {fmEmployeeDateAvailabilityModifier},
  fEmployeesAvailability in 'fEmployeesAvailability.pas' {fmEmployeesAvailability},
  fEmployeesAvailabilityFilter in 'fEmployeesAvailabilityFilter.pas' {fmEmployeesAvailabilityFilter},
  fEmployeeDateShiftCycles in 'fEmployeeDateShiftCycles.pas' {fmEmployeeDateShiftCycles},
  fShiftRegimeCalendar in 'fShiftRegimeCalendar.pas' {fmShiftRegimeCalendar},
  fEmployeePresenceDeviation in 'fEmployeePresenceDeviation.pas' {fmEmployeePresenceDeviation},
  fEmployeePresenceDeviationFilter in 'fEmployeePresenceDeviationFilter.pas' {fmEmployeePresenceDeviationFilter},
  rEmployeePresenceDeviation in 'rEmployeePresenceDeviation.pas' {rptEmployeePresenceDeviation: TQuickRep},
  rEmployeeMonthAvailability in 'rEmployeeMonthAvailability.pas' {rptEmployeeMonthAvailability: TQuickRep},
  fEmployeesTotalAvailability in 'fEmployeesTotalAvailability.pas' {fmEmployeesTotalAvailability},
  fEmployeesTotalAvailabilityFilter in 'fEmployeesTotalAvailabilityFilter.pas' {fmEmployeesTotalAvailabilityFilter},
  uEmployeeAvailability in '..\Common\uEmployeeAvailability.pas',
  fEmployeesAvailabilityGraph in 'fEmployeesAvailabilityGraph.pas' {fmEmployeesAvailabilityGraph},
  fEmployeesAvailabilityGraphFilter in 'fEmployeesAvailabilityGraphFilter.pas' {fmEmployeesAvailabilityGraphFilter},
  fEmployeeDayAbsences in 'fEmployeeDayAbsences.pas' {fmEmployeeDayAbsences},
  fEmployeeDayAbsencesFilter in 'fEmployeeDayAbsencesFilter.pas' {fmEmployeeDayAbsencesFilter},
  rShiftRegimeCalendar in 'rShiftRegimeCalendar.pas' {rptShiftRegimeCalendar},
  uShiftRegimeCalendarUtils in 'uShiftRegimeCalendarUtils.pas',
  fTimeFieldEditFrame in 'fTimeFieldEditFrame.pas' {frTimeFieldEditFrame: TFrame},
  rEmployeesAvailabilityGraph in 'rEmployeesAvailabilityGraph.pas' {rptEmployeesAvailabilityGraph: TQuickRep},
  fPartnerExFieldEditFrame in 'fPartnerExFieldEditFrame.pas' {frPartnerExFieldEditFrame: TFrame},
  rEmployeeDisciplineEvents in 'rEmployeeDisciplineEvents.pas' {rptEmployeeDisciplineEvents: TQuickRep},
  fProfessionIntervalEdit in 'fProfessionIntervalEdit.pas' {fmProfessionIntervalEdit},
  uSaleDealTypes in '..\Common\uSaleDealTypes.pas',
  fSaleOrder in 'fSaleOrder.pas' {fmSaleOrder},
  fPrecisionLevels in 'fPrecisionLevels.pas' {fmPrecisionLevels},
  fPrecisionLevel in 'fPrecisionLevel.pas' {fmPrecisionLevel},
  fDocItemSysRoles in 'fDocItemSysRoles.pas' {fmDocItemSysRoles},
  fDocItemSysRole in 'fDocItemSysRole.pas' {fmDocItemSysRole},
  fOccupationSalaries in 'fOccupationSalaries.pas' {fmOccupationSalaries},
  fOccupationSalary in 'fOccupationSalary.pas' {fmOccupationSalary},
  fParRel in 'fParRel.pas' {fmParRel},
  fParRelPeriod in 'fParRelPeriod.pas' {fmParRelPeriod},
  uBorderRelTypes in '..\Common\uBorderRelTypes.pas',
  fSaleRequestGroup in 'fSaleRequestGroup.pas' {fmSaleRequestGroup},
  fSaleRequestGroups in 'fSaleRequestGroups.pas' {fmSaleRequestGroups},
  fSaleRequestGroupsFilter in 'fSaleRequestGroupsFilter.pas' {fmSaleRequestGroupsFilter},
  fParRelProductsFilter in 'fParRelProductsFilter.pas' {fmParRelProductsFilter},
  fFailedEmployeeMovements in 'fFailedEmployeeMovements.pas' {fmFailedEmployeeMovements},
  fParRelProducts in 'fParRelProducts.pas' {fmParRelProducts},
  fProductPeriods in 'fProductPeriods.pas' {fmProductPeriods},
  fProductPeriod in 'fProductPeriod.pas' {fmProductPeriod},
  uIntToText in '..\Common\uIntToText.pas',
  fPoolManagers in 'fPoolManagers.pas' {fmPoolManagers},
  fMemoryManager in 'fMemoryManager.pas' {fmMemoryManager},
  fSaleOrders in 'fSaleOrders.pas' {fmSaleOrders},
  fSaleOrdersGroupSaleOrders in 'fSaleOrdersGroupSaleOrders.pas' {fmSaleOrdersGroupSaleOrders},
  fSaleOrdersGroupSaleOrdersFilter in 'fSaleOrdersGroupSaleOrdersFilter.pas' {fmSaleOrdersGroupSaleOrdersFilter},
  fSaleOrdersFilter in 'fSaleOrdersFilter.pas' {fmSaleOrdersFilter},
  uParRelProducts in 'uParRelProducts.pas',
  fGroupSale in 'fGroupSale.pas' {fmGroupSale},
  fParRelProduct in 'fParRelProduct.pas' {fmParRelProduct},
  fCompanyStatus in 'fCompanyStatus.pas' {frCompanyStatus: TFrame},
  fStatusesAbstract in 'fStatusesAbstract.pas' {fmStatusesAbstract},
  fParRelProductStatus in 'fParRelProductStatus.pas' {frParRelProductStatus: TFrame},
  fParRelProductStatuses in 'fParRelProductStatuses.pas' {fmParRelProductStatuses},
  fProductExFieldEditFrame in 'fProductExFieldEditFrame.pas' {frProductExFieldEditFrame: TFrame},
  fParRelProductStatusForm in 'fParRelProductStatusForm.pas' {fmParRelProductStatus},
  fParRelProductPeriod in 'fParRelProductPeriod.pas' {fmParRelProductPeriod},
  fNewParRelProductFilter in 'fNewParRelProductFilter.pas' {fmNewParRelProductFilter},
  fDeliveryStoreDeals in 'fDeliveryStoreDeals.pas' {fmDeliveryStoreDeals},
  uAspectTypes in '..\Common\uAspectTypes.pas',
  uNeeds in 'uNeeds.pas',
  fVendorProductSignaturesFilter in 'fVendorProductSignaturesFilter.pas' {fmVendorProductSignaturesFilter},
  fSpecInvestedValuesGraph in 'fSpecInvestedValuesGraph.pas' {fmSpecInvestedValuesGraph},
  fSpecInvestedValuesGraphFilter in 'fSpecInvestedValuesGraphFilter.pas' {fmSpecInvestedValuesGraphFilter},
  fDeliveryDialogs in 'fDeliveryDialogs.pas' {fmDeliveryDialogs},
  fTreeOnlyNomForm in 'Abstract\fTreeOnlyNomForm.pas' {TreeOnlyNomForm},
  fTreeOnlyNodeFieldEditFrame in 'Abstract\fTreeOnlyNodeFieldEditFrame.pas' {TreeOnlyNodeFieldEditFrame: TFrame},
  uSplitInvestedValue in 'uSplitInvestedValue.pas',
  fPriceList in 'fPriceList.pas' {fmPriceList},
  fPriceListFilter in 'fPriceListFilter.pas' {fmPriceListFilter},
  fRequirementAbstract in 'fRequirementAbstract.pas' {fmRequirementAbstract},
  uToolRequirements in 'uToolRequirements.pas',
  fToolRequirement in 'fToolRequirement.pas' {fmToolRequirement},
  fDeliveryDialogsFilter in 'fDeliveryDialogsFilter.pas' {fmDeliveryDialogsFilter},
  fOrganisationTaskProposals in 'fOrganisationTaskProposals.pas' {fmOrganisationTaskProposals},
  fOrganisationTaskProposal in 'fOrganisationTaskProposal.pas' {fmOrganisationTaskProposal},
  fOrganisationTaskProposalsFilter in 'fOrganisationTaskProposalsFilter.pas' {fmOrganisationTaskProposalsFilter},
  uOrganisationTaskUtils in '..\Common\uOrganisationTaskUtils.pas',
  uOrganisationTaskClientUtils in 'uOrganisationTaskClientUtils.pas',
  fEstQuantitiesTable in 'fEstQuantitiesTable.pas' {fmEstQuantitiesTable},
  fEstQuantitiesFilterAbstract in 'fEstQuantitiesFilterAbstract.pas' {fmEstQuantitiesFilterAbstract},
  fEstQuantitiesGraph in 'fEstQuantitiesGraph.pas' {fmEstQuantitiesGraph},
  fEstQuantitiesTableFilter in 'fEstQuantitiesTableFilter.pas' {fmEstQuantitiesTableFilter},
  fEstQuantitiesGraphFilter in 'fEstQuantitiesGraphFilter.pas' {fmEstQuantitiesGraphFilter},
  fEstPricesCompareGraph in 'fEstPricesCompareGraph.pas' {fmEstPricesCompareGraph},
  fEstPricesCompareGraphFilter in 'fEstPricesCompareGraphFilter.pas' {fmEstPricesCompareGraphFilter},
  uDeliveryDealTypes in '..\Common\uDeliveryDealTypes.pas',
  fDeliveryTypes in 'fDeliveryTypes.pas' {fmDeliveryTypes},
  fDeliveryType in 'fDeliveryType.pas' {fmDeliveryType},
  fStoreDealBindingFilter in 'fStoreDealBindingFilter.pas' {frStoreDealBindingFilter: TFrame},
  fDisciplineEventTypesTree in 'fDisciplineEventTypesTree.pas' {fmDisciplineEventTypesTree},
  fDisciplineEventTypeEdit in 'fDisciplineEventTypeEdit.pas' {fmDisciplineEventTypeEdit},
  fDisciplineEventTypePeriod in 'fDisciplineEventTypePeriod.pas' {fmDisciplineEventTypePeriod},
  fDiscEventTypeFieldEditFrame in 'fDiscEventTypeFieldEditFrame.pas' {frDiscEventTypeFieldEditFrame: TFrame},
  fDisciplineEvents in 'fDisciplineEvents.pas' {fmDisciplineEvents},
  fDisciplineEventsFilter in 'fDisciplineEventsFilter.pas' {fmDisciplineEventsFilter},
  rDisciplineEvents in 'rDisciplineEvents.pas' {rptDisciplineEvents: TQuickRep},
  uStreamTypes in '..\Common\uStreamTypes.pas',
  rVendorProductSignatures in 'rVendorProductSignatures.pas' {rptVendorProductSignatures: TQuickRep},
  rStructureXModel in 'rStructureXModel.pas' {rptStructureXModel: TQuickRep},
  rXModel in 'rXModel.pas' {rptXModel: TQuickRep},
  rGroupSalesDetail in 'rGroupSalesDetail.pas' {rptGroupSalesDetail: TQuickRep},
  rSaleRequestGroups in 'rSaleRequestGroups.pas' {rptSaleRequestGroups: TQuickRep},
  uInvoiceVatTypes in 'uInvoiceVatTypes.pas',
  fExceptEvent in 'fExceptEvent.pas' {fmExceptEvent},
  fExceptEventDamage in 'fExceptEventDamage.pas' {fmExceptEventDamage},
  fExceptEventDamageAttack in 'fExceptEventDamageAttack.pas' {fmExceptEventDamageAttack},
  fExceptEvents in 'fExceptEvents.pas' {fmExceptEvents},
  fExceptEventTask in 'fExceptEventTask.pas' {fmExceptEventTask},
  fExceptEventIdentification in 'fExceptEventIdentification.pas' {frExceptEventIdentification: TFrame},
  uExceptEventClientUtils in 'uExceptEventClientUtils.pas',
  fExceptEventsFilter in 'fExceptEventsFilter.pas' {fmExceptEventsFilter},
  rSale in 'rSale.pas' {rptSale: TQuickRep},
  fStoreDeals in 'fStoreDeals.pas' {fmStoreDeals},
  xTextMessages in 'xTextMessages.pas',
  uBOIOrderTypes in '..\Common\uBOIOrderTypes.pas',
  fSpecInvestedValueLevelsGraph in 'fSpecInvestedValueLevelsGraph.pas' {fmSpecInvestedValueLevelsGraph},
  fSpecInvestedValueLevelsGraphFilter in 'fSpecInvestedValueLevelsGraphFilter.pas' {fmSpecInvestedValueLevelsGraphFilter},
  fCompanyTypes in 'fCompanyTypes.pas' {fmCompanyTypes},
  fDeliveryDecisions in 'fDeliveryDecisions.pas' {fmDeliveryDecisions},
  fDeliveryDecision in 'fDeliveryDecision.pas' {fmDeliveryDecision},
  fSaleDecisionTypes in 'fSaleDecisionTypes.pas' {fmSaleDecisionTypes},
  fSaleDecisionType in 'fSaleDecisionType.pas' {fmSaleDecisionType},
  fCompanyType in 'fCompanyType.pas' {fmCompanyType},
  uBorderRelTypeClientUtils in 'uBorderRelTypeClientUtils.pas',
  uCompanyKindClientUtils in 'uCompanyKindClientUtils.pas',
  uProductClientUtils in 'uProductClientUtils.pas',
  uSalesClientUtils in 'uSalesClientUtils.pas',
  uBOIDistributionTypes in '..\Common\uBOIDistributionTypes.pas',
  uYearParts in 'uYearParts.pas',
  uFinModelLineTypes in 'uFinModelLineTypes.pas',
  fSpecFinModel in 'fSpecFinModel.pas' {fmSpecFinModel},
  fSpecFinModelLine in 'fSpecFinModelLine.pas' {fmSpecFinModelLine},
  uDataSetUtils in 'uDataSetUtils.pas',
  fFinModelLineReasons in 'fFinModelLineReasons.pas' {fmFinModelLineReasons},
  fFinModelLineReason in 'fFinModelLineReason.pas' {fmFinModelLineReason},
  fFinClassesTree in 'fFinClassesTree.pas' {fmFinClassesTree},
  fFinClassEdit in 'fFinClassEdit.pas' {fmFinClassEdit},
  fFinClassFieldEditFrame in 'fFinClassFieldEditFrame.pas' {frFinClassFieldEditFrame: TFrame},
  fFinClassFieldEditFrameBald in 'fFinClassFieldEditFrameBald.pas' {frFinClassFieldEditFrameBald: TFrame},
  fFinClassFieldEditFrameLabeled in 'fFinClassFieldEditFrameLabeled.pas' {frFinClassFieldEditFrameLabeled: TFrame},
  fFinOrder in 'fFinOrder.pas' {fmFinOrder},
  uFinanceClientUtils in 'uFinanceClientUtils.pas',
  uClientLoginContext in 'uClientLoginContext.pas',
  fFinOrders in 'fFinOrders.pas' {fmFinOrders},
  fFinOrdersFilter in 'fFinOrdersFilter.pas' {fmFinOrdersFilter},
  fRealFinModelLine in 'fRealFinModelLine.pas' {fmRealFinModelLine},
  fRealFinModelLines in 'fRealFinModelLines.pas' {fmRealFinModelLines},
  fRealFinModelLinesFilter in 'fRealFinModelLinesFilter.pas' {fmRealFinModelLinesFilter},
  fFinOrderLineProcessObject in 'fFinOrderLineProcessObject.pas' {frFinOrderLineProcessObject: TFrame},
  fRealFinModelLineGroups in 'fRealFinModelLineGroups.pas' {fmRealFinModelLineGroups},
  uOccupationUtils in '..\Common\uOccupationUtils.pas',
  fNewFinOrder in 'fNewFinOrder.pas' {fmNewFinOrder},
  fSelectSpecFinModel in 'fSelectSpecFinModel.pas' {fmSelectSpecFinModel},
  fSysRoles in 'fSysRoles.pas' {fmSysRoles},
  fSysRole in 'fSysRole.pas' {fmSysRole},
  fSysRoleFieldEditFrame in 'fSysRoleFieldEditFrame.pas' {frSysRoleFieldEditFrame: TFrame},
  fSysRoleFieldEditFrameLabeled in 'fSysRoleFieldEditFrameLabeled.pas' {frSysRoleFieldEditFrameLabeled: TFrame},
  fOccupationEffectiveActivities in 'fOccupationEffectiveActivities.pas' {fmOccupationEffectiveActivities},
  fSysRoleFieldEditFrameBald in 'fSysRoleFieldEditFrameBald.pas' {frSysRoleFieldEditFrameBald: TFrame},
  fUserEffectiveActivitiesFilter in 'fUserEffectiveActivitiesFilter.pas' {fmUserEffectiveActivitiesFilter},
  fUser in 'fUser.pas' {fmUser},
  fUserMemberGroups in 'fUserMemberGroups.pas' {fmUserMemberGroups},
  fFinancialRelationsGraph in 'fFinancialRelationsGraph.pas' {fmFinancialRelationsGraph},
  fFinancialRelationsAbstractFilter in 'fFinancialRelationsAbstractFilter.pas' {fmFinancialRelationsAbstractFilter},
  fFinancialRelationsGraphFilter in 'fFinancialRelationsGraphFilter.pas' {fmFinancialRelationsGraphFilter},
  fFinancialRelationsTable in 'fFinancialRelationsTable.pas' {fmFinancialRelationsTable},
  fFinancialRelationsTableFilter in 'fFinancialRelationsTableFilter.pas' {fmFinancialRelationsTableFilter},
  uFinOrderRequirementClientUtils in 'uFinOrderRequirementClientUtils.pas',
  rSaleLease in 'rSaleLease.pas' {rptSaleLease: TQuickRep},
  fSpecOperationsInvestedValues in 'fSpecOperationsInvestedValues.pas' {fmSpecOperationsInvestedValues},
  fXModelOperationsInvestedValues in 'fXModelOperationsInvestedValues.pas' {fmXModelOperationsInvestedValues},
  rSpecAndXModelOperationsInvestedValues in 'rSpecAndXModelOperationsInvestedValues.pas' {rptSpecAndXModelOperationsInvestedValues: TQuickRep},
  rSpecOperationsInvestedValues in 'rSpecOperationsInvestedValues.pas' {rptSpecOperationsInvestedValues: TQuickRep},
  rXModelOperationsInvestedValues in 'rXModelOperationsInvestedValues.pas' {rptXModelOperationsInvestedValues: TQuickRep},
  fTestQueries in 'fTestQueries.pas' {fmTestQueries},
  fDeptDetailFlowToolNeeds in 'fDeptDetailFlowToolNeeds.pas' {fmDeptDetailFlowToolNeeds},
  uDeptDetailFlow in '..\Common\uDeptDetailFlow.pas',
  fOrgTaskProposalCodeEdit in 'fOrgTaskProposalCodeEdit.pas' {fmOrgTaskProposalCodeEdit},
  fChooseExceptEvent in 'fChooseExceptEvent.pas' {fmChooseExceptEvent},
  uCombImageList in 'uCombImageList.pas',
  fActiveConnections in 'fActiveConnections.pas' {fmActiveConnections},
  fRealFinModelLineGroupsFilter in 'fRealFinModelLineGroupsFilter.pas' {fmRealFinModelLineGroupsFilter},
  uClientDateTime in 'uClientDateTime.pas',
  fSetContextDate in 'fSetContextDate.pas' {fmSetContextDate},
  uLicenseUtils in '..\Common\uLicenseUtils.pas',
  rOrganisationTaskProposals in 'rOrganisationTaskProposals.pas' {rptOrganisationTaskProposals: TQuickRep},
  uCellParamsSetters in 'uCellParamsSetters.pas',
  uToolbarUtils in 'uToolbarUtils.pas',
  fSysRolesFilter in 'fSysRolesFilter.pas' {fmSysRolesFilter},
  fEnumFieldEditFrame in 'Abstract\fEnumFieldEditFrame.pas' {EnumFieldEditFrame: TFrame},
  fActivityFieldEditFrame in 'fActivityFieldEditFrame.pas' {frActivityFieldEditFrame: TFrame},
  fBaseGroupsCandidateProductsFilter in 'fBaseGroupsCandidateProductsFilter.pas' {fmBaseGroupsCandidateProductsFilter},
  uSysRoleClientUtils in 'uSysRoleClientUtils.pas',
  fBudgetGraph in 'fBudgetGraph.pas' {fmBudgetGraph},
  fOccSysRolesFilter in 'fOccSysRolesFilter.pas' {fmOccSysRolesFilter},
  rBOIOrderAbstract in 'rBOIOrderAbstract.pas' {rptBOIOrderAbstract: TQuickRep},
  rBOICompanyOrder in 'rBOICompanyOrder.pas' {rptBOICompanyOrder: TQuickRep},
  rBOIWasteOrder in 'rBOIWasteOrder.pas' {rptBOIWasteOrder: TQuickRep},
  rBOIProductOrder in 'rBOIProductOrder.pas' {rptBOIProductOrder: TQuickRep},
  fProcessActions in 'fProcessActions.pas' {fmProcessActions},
  fProcessAction in 'fProcessAction.pas' {fmProcessAction},
  fProcessKnowlsTree in 'fProcessKnowlsTree.pas' {fmProcessKnowlsTree},
  fProcessKnowlEdit in 'fProcessKnowlEdit.pas' {fmProcessKnowlEdit},
  fProcessFunctionsTree in 'fProcessFunctionsTree.pas' {fmProcessFunctionsTree},
  fProcessFunctionEdit in 'fProcessFunctionEdit.pas' {fmProcessFunctionEdit},
  fProcessBaseOperationsTree in 'fProcessBaseOperationsTree.pas' {fmProcessBaseOperationsTree},
  fProcessBaseOperationEdit in 'fProcessBaseOperationEdit.pas' {fmProcessBaseOperationEdit},
  fProcessConcreteOperationsTree in 'fProcessConcreteOperationsTree.pas' {fmProcessConcreteOperationsTree},
  fProcessConcreteOperationEdit in 'fProcessConcreteOperationEdit.pas' {fmProcessConcreteOperationEdit},
  fProcessConcreteOperationFieldEditFrame in 'fProcessConcreteOperationFieldEditFrame.pas' {frProcessConcreteOperationFieldEditFrame: TFrame},
  fProcessBaseOperationFieldEditFrame in 'fProcessBaseOperationFieldEditFrame.pas' {frProcessBaseOperationFieldEditFrame: TFrame},
  fProcessConcreteOperationFieldEditFrameBald in 'fProcessConcreteOperationFieldEditFrameBald.pas' {frProcessConcreteOperationFieldEditFrameBald: TFrame},
  uPrcDeclarations in '..\Common\uPrcDeclarations.pas',
  uPrcUtils in '..\Common\uPrcUtils.pas',
  fPrcDataFieldEditFrame in 'fPrcDataFieldEditFrame.pas' {frPrcDataFieldEditFrame: TFrame},
  uPrcData in '..\Common\uPrcData.pas',
  uClientPrcData in 'uClientPrcData.pas',
  uPrcEditForms in 'uPrcEditForms.pas',
  fPrcDataProcessActionWithDateInterval in 'fPrcDataProcessActionWithDateInterval.pas' {fmPrcDataProcessActionWithDateInterval},
  fProcessKnowlFieldEditFrame in 'fProcessKnowlFieldEditFrame.pas' {frProcessKnowlFieldEditFrame: TFrame},
  fProcessKnowlFieldEditFrameBald in 'fProcessKnowlFieldEditFrameBald.pas' {frProcessKnowlFieldEditFrameBald: TFrame},
  fProcessKnowlFieldEditFrameLabeled in 'fProcessKnowlFieldEditFrameLabeled.pas' {frProcessKnowlFieldEditFrameLabeled: TFrame},
  fProcessFunctionFieldEditFrame in 'fProcessFunctionFieldEditFrame.pas' {frProcessFunctionFieldEditFrame: TFrame},
  fProcessFunctionFieldEditFrameBald in 'fProcessFunctionFieldEditFrameBald.pas' {frProcessFunctionFieldEditFrameBald: TFrame},
  fProcessFunctionFieldEditFrameLabeled in 'fProcessFunctionFieldEditFrameLabeled.pas' {frProcessFunctionFieldEditFrameLabeled: TFrame},
  fProcessBaseOperationFieldEditFrameBald in 'fProcessBaseOperationFieldEditFrameBald.pas' {frProcessBaseOperationFieldEditFrameBald: TFrame},
  fProcessBaseOperationFieldEditFrameLabeled in 'fProcessBaseOperationFieldEditFrameLabeled.pas' {frProcessBaseOperationFieldEditFrameLabeled: TFrame},
  fProcessConcreteOperationFieldEditFrameLabeled in 'fProcessConcreteOperationFieldEditFrameLabeled.pas' {frProcessConcreteOperationFieldEditFrameLabeled: TFrame},
  fProcessActionFieldEditFrame in 'fProcessActionFieldEditFrame.pas' {frProcessActionFieldEditFrame: TFrame},
  fPrcDataConcreteOp in 'fPrcDataConcreteOp.pas' {fmPrcDataConcreteOp},
  fPrcActionLearningStatuses in 'fPrcActionLearningStatuses.pas' {fmPrcActionLearningStatuses},
  fPrcActionLearningStatus in 'fPrcActionLearningStatus.pas' {fmPrcActionLearningStatus},
  uComboBoxUtils in 'uComboBoxUtils.pas',
  fBOIMarkingOrders in 'fBOIMarkingOrders.pas' {fmBOIMarkingOrders},
  fBOIMarkingOrdersFilter in 'fBOIMarkingOrdersFilter.pas' {fmBOIMarkingOrdersFilter},
  fBOIMarkingOrder in 'fBOIMarkingOrder.pas' {fmBOIMarkingOrder},
  uBudgetUtils in '..\Common\uBudgetUtils.pas',
  uBudgetReportUtils in 'uBudgetReportUtils.pas',
  rBOIMarkingOrdersDetail in 'rBOIMarkingOrdersDetail.pas' {rptBOIMarkingOrdersDetail: TQuickRep},
  rBOIMarkingOrder in 'rBOIMarkingOrder.pas' {rptBOIMarkingOrder: TQuickRep},
  fProfessionFieldEditFrame in 'fProfessionFieldEditFrame.pas' {frProfessionFieldEditFrame: TFrame},
  fProfessionFieldEditFrameBald in 'fProfessionFieldEditFrameBald.pas' {frProfessionFieldEditFrameBald: TFrame},
  rPrcDataReport in 'Abstract\rPrcDataReport.pas' {PrcDataReport: TQuickRep},
  rDBTreeDataReport in 'Abstract\rDBTreeDataReport.pas' {DBTreeDataReport: TQuickRep},
  rOrgTaskProposalPrcDataReport in 'rOrgTaskProposalPrcDataReport.pas' {rptOrgTaskProposalPrcDataReport: TQuickRep},
  rDeptPrcDataReport in 'rDeptPrcDataReport.pas' {rptDeptPrcDataReport: TQuickRep},
  rProcessFunctionPrcDataReport in 'rProcessFunctionPrcDataReport.pas' {rptProcessFunctionPrcDataReport: TQuickRep},
  rOccupationPrcDataReport in 'rOccupationPrcDataReport.pas' {rptOccupationPrcDataReport: TQuickRep},
  rOccupationAndEmployeePrcDataReport in 'rOccupationAndEmployeePrcDataReport.pas' {rptOccupationAndEmployeePrcDataReport: TQuickRep},
  uWndProcHooker in '..\Common\uWndProcHooker.pas',
  uNestProc in '..\Common\uNestProc.pas',
  fSaleRequestLineProcessObject in 'fSaleRequestLineProcessObject.pas' {frSaleRequestLineProcessObject: TFrame},
  fVatPeriods in 'fVatPeriods.pas' {fmVatPeriods},
  fVatPeriod in 'fVatPeriod.pas' {fmVatPeriod},
  uEnumeratorUtils in '..\Common\uEnumeratorUtils.pas',
  uXMLEnumerators in '..\Common\uXMLEnumerators.pas',
  uChosenNodes in '..\Common\uChosenNodes.pas',
  fPrcDataFuncKnowl in 'fPrcDataFuncKnowl.pas' {fmPrcDataFuncKnowl},
  fPrcDataFuncKnowlBaseOp in 'fPrcDataFuncKnowlBaseOp.pas' {fmPrcDataFuncKnowlBaseOp},
  fCompanyConcretePartners in 'fCompanyConcretePartners.pas' {fmCompanyConcretePartners},
  uCompanyClasses in '..\Common\uCompanyClasses.pas',
  fProductPartnerPrice in 'fProductPartnerPrice.pas' {fmProductPartnerPrice},
  rProductPartnerPrice in 'rProductPartnerPrice.pas' {rptProductPartnerPrice: TQuickRep},
  fProductSets in 'fProductSets.pas' {fmProductSets},
  fProductSet in 'fProductSet.pas' {fmProductSet},
  fPRPerPriceModifiers in 'fPRPerPriceModifiers.pas' {fmPRPerPriceModifiers},
  fPRPerPriceModifier in 'fPRPerPriceModifier.pas' {fmPRPerPriceModifier},
  fProductSetFieldEditFrame in 'fProductSetFieldEditFrame.pas' {frProductSetFieldEditFrame: TFrame},
  fPRPerPriceModifierProductSetFieldEditFrame in 'fPRPerPriceModifierProductSetFieldEditFrame.pas' {frPRPerPriceModifierProductSetFieldEditFrame: TFrame},
  uBankAccountTypes in '..\Common\uBankAccountTypes.pas',
  uAutoMouseWheel in 'uAutoMouseWheel.pas',
  uClientStoreUtils in 'uClientStoreUtils.pas',
  uCompanyStatuses in 'uCompanyStatuses.pas',
  uObjectSubscription in '..\Common\uObjectSubscription.pas',
  uFMMovementOffsetTypes in '..\Common\uFMMovementOffsetTypes.pas',
  uCompanyUtils in '..\Common\uCompanyUtils.pas',
  fRealFinModelLineGroup in 'fRealFinModelLineGroup.pas' {fmRealFinModelLineGroup},
  fSpecInvestedValuesLevel1 in 'fSpecInvestedValuesLevel1.pas' {fmSpecInvestedValuesLevel1},
  rSpecInvestedValuesLevel1 in 'rSpecInvestedValuesLevel1.pas' {rptSpecInvestedValuesLevel1: TQuickRep},
  fPrcDataFunc in 'fPrcDataFunc.pas' {fmPrcDataFunc},
  fPrcDataKnowl in 'fPrcDataKnowl.pas' {fmPrcDataKnowl},
  fPrcDataBaseOp in 'fPrcDataBaseOp.pas' {fmPrcDataBaseOp},
  fPrcDataProcessAction in 'fPrcDataProcessAction.pas' {fmPrcDataProcessAction},
  fSelectProduct in 'fSelectProduct.pas' {fmSelectProduct},
  fProcessConcreteOperation in 'fProcessConcreteOperation.pas' {fmProcessConcreteOperation},
  fProcessBaseOperation in 'fProcessBaseOperation.pas' {fmProcessBaseOperation},
  uSection in '..\Common\uSection.pas',
  uProfessionTypes in '..\Common\uProfessionTypes.pas',
  fReconnect in 'fReconnect.pas' {fmReconnect},
  uClientPrcUtils in 'uClientPrcUtils.pas',
  fChangeCurrentPrinter in 'fChangeCurrentPrinter.pas' {fmChangeCurrentPrinter},
  uFieldTextVisibility in 'uFieldTextVisibility.pas',
  fProcessActionFieldEditFrameBald in 'fProcessActionFieldEditFrameBald.pas' {frProcessActionFieldEditFrameBald: TFrame},
  fOrganisationPrcData in 'fOrganisationPrcData.pas' {fmOrganisationPrcData},
  fPrcDataFilterFrame in 'fPrcDataFilterFrame.pas' {frPrcDataFilterFrame: TFrame},
  rOrganisationPrcDataReport in 'rOrganisationPrcDataReport.pas' {rptOrganisationPrcDataReport: TQuickRep},
  fOrgPrcDataDistribution in 'fOrgPrcDataDistribution.pas' {fmOrgPrcDataDistribution},
  fOrgPrcDataDistributionFilter in 'fOrgPrcDataDistributionFilter.pas' {fmOrgPrcDataDistributionFilter},
  uAttachedProperty in '..\Common\uAttachedProperty.pas',
  uDependantField in 'uDependantField.pas',
  rFinOrders in 'rFinOrders.pas' {rptFinOrders: TQuickRep},
  fDeptsPrcData in 'fDeptsPrcData.pas' {fmDeptsPrcData},
  fDeptsPrcDataFilter in 'fDeptsPrcDataFilter.pas' {fmDeptsPrcDataFilter},
  uTotalCountField in 'uTotalCountField.pas',
  fDeptPrcData in 'fDeptPrcData.pas' {fmDeptPrcData},
  uAttributeUtils in '..\Common\uAttributeUtils.pas',
  uFuncUtils in '..\Common\uFuncUtils.pas',
  fFinModelLineStoreDeals in 'fFinModelLineStoreDeals.pas' {frRealFinModelLineStoreDeals: TFrame},
  fFilterFrameBaseFilter in 'fFilterFrameBaseFilter.pas' {fmFilterFrameBaseFilter},
  fFilterFrame in 'Abstract\fFilterFrame.pas' {FilterFrame: TFrame},
  fTreeNodeGridFilter in 'Abstract\fTreeNodeGridFilter.pas' {frTreeNodeGridFilter: TFrame},
  fOrgWorkActivities in 'fOrgWorkActivities.pas' {fmOrgWorkActivities},
  fOrgWorkActivity in 'fOrgWorkActivity.pas' {fmOrgWorkActivity},
  uOWDPriorityTypes in '..\Common\uOWDPriorityTypes.pas',
  fDeptOWDPriorities in 'fDeptOWDPriorities.pas' {frDeptOWDPriorities: TFrame},
  fDeptOWDPriority in 'fDeptOWDPriority.pas' {fmDeptOWDPriority},
  uOWDPriorityStates in 'uOWDPriorityStates.pas',
  uOWDPriorityClientConsts in 'uOWDPriorityClientConsts.pas',
  uAbmesClientDataSetHelper in '..\Common\uAbmesClientDataSetHelper.pas',
  uParallelUtils in '..\Common\uParallelUtils.pas',
  rRealFinModelLineGroups in 'rRealFinModelLineGroups.pas' {rptRealFinModelLineGroups: TQuickRep},
  uDocItemStorageTypes in '..\Common\uDocItemStorageTypes.pas',
  fContactTypes in 'fContactTypes.pas' {fmContactTypes},
  fContactType in 'fContactType.pas' {fmContactType},
  uDBChartSeriesClickFixer in 'uDBChartSeriesClickFixer.pas',
  uDocExcelExport in 'uDocExcelExport.pas',
  fDocExcelExport in 'fDocExcelExport.pas' {fmDocExcelExport},
  uDCDModes in '..\Common\uDCDModes.pas',
  uRttiUtils in '..\Common\uRttiUtils.pas',
  fDeliveriesInvoiceData in 'fDeliveriesInvoiceData.pas' {fmDeliveriesInvoiceData},
  fDeliveriesMultiDecisionData in 'fDeliveriesMultiDecisionData.pas' {fmDeliveriesMultiDecisionData},
  uClientProxies in '..\Server\uClientProxies.pas',
  fQuantityDeficitCreateDeliveryProjects in 'fQuantityDeficitCreateDeliveryProjects.pas' {fmQuantityDeficitCreateDeliveryProjects},
  uConnectionUtils in '..\Common\uConnectionUtils.pas',
  uTreeListUtils in 'uTreeListUtils.pas',
  fQuantityDeficitCreateDeliveryProjectsEdit in 'fQuantityDeficitCreateDeliveryProjectsEdit.pas' {fmQuantityDeficitCreateDeliveryProjectsEdit},
  fGridTreeListExpanderFrame in 'fGridTreeListExpanderFrame.pas' {frGridTreeListExpanderFrame: TFrame},
  fVatReasons in 'fVatReasons.pas' {fmVatReasons},
  fVatReason in 'fVatReason.pas' {fmVatReason},
  uJvComboEditFixer in 'uJvComboEditFixer.pas',
  rIInvoice in 'rIInvoice.pas' {rptIInvoice: TQuickRep},
  fProfessionsTree in 'fProfessionsTree.pas' {fmProfessionsTree},
  uSystemLocaleUtils in '..\Common\uSystemLocaleUtils.pas',
  uVariantMemoryMap in '..\Common\uVariantMemoryMap.pas',
  fInvoiceNoGenerators in 'fInvoiceNoGenerators.pas' {fmInvoiceNoGenerators},
  fInvoiceNoGenerator in 'fInvoiceNoGenerator.pas' {fmInvoiceNoGenerator},
  fDefaultDocItem in 'fDefaultDocItem.pas' {fmDefaultDocItem},
  fCompleteFinOrder in 'fCompleteFinOrder.pas' {fmCompleteFinOrder},
  fDocProfiles in 'fDocProfiles.pas' {fmDocProfiles},
  fDocProfile in 'fDocProfile.pas' {fmDocProfile},
  fDocProfileSelector in 'fDocProfileSelector.pas' {fmDocProfileSelector},
  fDBGridSearch in 'fDBGridSearch.pas' {frDBGridSearch: TFrame},
  fExceptEventTypesTree in 'fExceptEventTypesTree.pas' {fmExceptEventTypesTree},
  fExceptEventTypeEdit in 'fExceptEventTypeEdit.pas' {fmExceptEventTypeEdit},
  fExceptEventTypeFieldEditFrame in 'fExceptEventTypeFieldEditFrame.pas' {frExceptEventTypeFieldEditFrame: TFrame},
  fExceptEventTypeFieldEditFrameLabeled in 'fExceptEventTypeFieldEditFrameLabeled.pas' {frExceptEventTypeFieldEditFrameLabeled: TFrame},
  fExceptEventTypeFieldEditFrameBald in 'fExceptEventTypeFieldEditFrameBald.pas' {frExceptEventTypeFieldEditFrameBald: TFrame},
  fChooseDelivery in 'fChooseDelivery.pas' {fmChooseDelivery},
  fDefaultPrinters in 'fDefaultPrinters.pas' {fmDefaultPrinters},
  uDefaultPrinters in 'uDefaultPrinters.pas',
  fDocItemStorageTypes in 'fDocItemStorageTypes.pas' {fmDocItemStorageTypes},
  fDocItemStorageType in 'fDocItemStorageType.pas' {fmDocItemStorageType},
  fExternalDocStorageDocId in 'fExternalDocStorageDocId.pas' {fmExternalDocStorageDocId},
  fSelectExternalDocId in 'fSelectExternalDocId.pas' {fmSelectExternalDocId},
  fAccessRules in 'fAccessRules.pas' {fmAccessRules},
  fAccessRule in 'fAccessRule.pas' {fmAccessRule},
  uPing in '..\Common\uPing.pas',
  uTaskBarUtils in 'uTaskBarUtils.pas',
  uDatabaseIcons in 'uDatabaseIcons.pas',
  fProductDeptOptionEdit in 'fProductDeptOptionEdit.pas' {fmProductDeptOptionEdit},
  fProductDeptOptions in 'fProductDeptOptions.pas' {fmProductDeptOptions},
  uDocItemStorageBaseTypes in '..\Common\uDocItemStorageBaseTypes.pas',
  fHyperlink in 'fHyperlink.pas' {fmHyperlink},
  uProgressHttp in 'uProgressHttp.pas',
  uTimerThread in 'uTimerThread.pas',
  dPing in 'dPing.pas' {dmPing: TDataModule},
  uClientConnectionInfo in 'uClientConnectionInfo.pas',
  uPingInfo in 'uPingInfo.pas',
  uIdentityModel.TokenClient in '..\Common\uIdentityModel.TokenClient.pas',
  uIdentityModel.Constants in '..\Common\uIdentityModel.Constants.pas',
  uIdentityServer.Constants in '..\Common\uIdentityServer.Constants.pas',
  uRecentUsers in 'uRecentUsers.pas',
  uIdentity.Connector in '..\Common\uIdentity.Connector.pas',
  uIdentity.Connector.Internal in '..\Common\uIdentity.Connector.Internal.pas',
  uClientApp in '..\..\App\uClientApp.pas',
  uContentStorage.Results in '..\Common\uContentStorage.Results.pas',
  uScalingUtils in 'uScalingUtils.pas',
  uComCtrlsHelpers in 'uComCtrlsHelpers.pas',
  uEhLibHelpers in 'uEhLibHelpers.pas',
  uAbmesDBGridHelpers in 'uAbmesDBGridHelpers.pas',
  uFilterField in 'uFilterField.pas',
  uIdentity.Manager in '..\Common\uIdentity.Manager.pas',
  uContentStorage.Utils in '..\Common\uContentStorage.Utils.pas',
  uCommonApp in '..\..\App\uCommonApp.pas',
  uAbmesDSProviderConnectionHelper in 'uAbmesDSProviderConnectionHelper.pas',
  uClientAppResources in '..\..\App\uClientAppResources.pas';

{$R *.RES}

begin
  Application.Initialize;
  Application.Title := SAppName;
  Application.CreateForm(TdmMain, dmMain);
  Application.CreateForm(TdmPing, dmPing);
  Application.CreateForm(TfmMain, fmMain);
  Application.CreateForm(TfmReportParent, fmReportParent);
  CheckAutoCreateForms;
  Application.HintHidePause:= MaxInt;  // cial jivot - dokato ne mrudnesh mishkata

  if not Application.Terminated then
    begin
      if (EditDefaultPrintersLocation <> dplNone) then
        EditDefaultPrinters
      else
        begin
          try
            if dmMain.ConnectUsingOuterLoginInfo or TfmLogin.ShowForm then
              begin
                Application.Run;
              end;
          finally
            dmMain.Finalize;
          end;
        end;
    end;
end.
