//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogImporter.Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderCallLogEntry
    {
        public int Id { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string Occurrence { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public string ProviderName { get; set; }
        public long FastMMAllocatedMemory { get; set; }
        public long FastMMReservedMemory { get; set; }
        public long WinMMAllocatedMemory { get; set; }
        public long ParamsMemory { get; set; }
        public Nullable<long> DurationMilliseconds { get; set; }
        public string DBName { get; set; }
        public int EmployeeCode { get; set; }
        public string ExceptionMessage { get; set; }
    }
}
