//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogImporter.Library.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServerLogsContainer : DbContext
    {
        public ServerLogsContainer()
            : base("name=ServerLogsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MethodCallLogEntry> MethodCallLogEntrySet { get; set; }
        public DbSet<ProviderCallLogEntry> ProviderCallLogEntrySet { get; set; }
    }
}
